if(typeof window.items == "undefined"){
    window.items = {};
}

$.extend(true, window.items, {
    itemMasters:{
        //Eyewear
        sunglasses:{
            itemType:"eyewear",
            clothingSlot:"eyewear",
            name:"Sunglasses",
            itemMaster: "sunglasses",
            daring:0,
            disabled:false,
            hasWorn:false,
            isMale:true,
            isFemale:true,
            tags:{
                plain:true,
            }
        },
        glasses:{
            itemType:"eyewear",
            clothingSlot:"eyewear",
            name:"Decorative Glasses",
            itemMaster: "glasses",
            daring:0,
            disabled:false,
            hasWorn:false,
            isMale:true,
            isFemale:true,
            tags:{
                plain:true,
            }
        },
        blindfold:{
            itemType:"eyewear",
            clothingSlot:"eyewear",
            name:"Blindfold",
            itemMaster: "blindfold",
            daring:0,
            disabled:false,
            hasWorn:false,
            isMale:true,
            isFemale:true,
            tags:{
                plain:true,
            }
        },
    },
    itemChildren:{
        //sunglasses
        sunglasses00:{
            masterItem:"sunglasses",
            variant:"sunglasses_00",
            name:"Aviator Sunglasses with Pink Lenses",
            price:20,
            daring:0,
            disabled:false,
            isMale:true,
            isFemale:true,
            isItemSet:false,
            setName:"",
            tags:{
                pink:true,
                plain:true,
            }
        },
        sunglasses01:{
            masterItem:"sunglasses",
            variant:"sunglasses_01",
            name:"Wayferer Sunglasses with Pink Frames",
            price:20,
            daring:0,
            disabled:false,
            isMale:false,
            isFemale:true,
            isItemSet:false,
            setName:"",
            tags:{
                pink:true,
                plain:true,
            }
        },
        sunglasses02:{
            masterItem:"sunglasses",
            variant:"sunglasses_02",
            name:"Wayferer Sunglasses with Pink and Black Frames",
            price:20,
            daring:0,
            disabled:false,
            isMale:false,
            isFemale:true,
            isItemSet:false,
            setName:"",
            tags:{
                pink:true,
                black:true,
                plain:true,
            }
        },
        sunglasses03:{
            masterItem:"sunglasses",
            variant:"sunglasses_03",
            name:"Pink Plastic Ladies Sunglasses",
            price:20,
            daring:0,
            disabled:false,
            isMale:false,
            isFemale:true,
            isItemSet:false,
            setName:"",
            tags:{
                pink:true,
                plain:true,
            }
        },
        sunglasses04:{
            masterItem:"sunglasses",
            variant:"sunglasses_04",
            name:"Black Ladies Sunglasses with Metal Decoration",
            price:20,
            daring:0,
            disabled:false,
            isMale:false,
            isFemale:true,
            isItemSet:false,
            setName:"",
            tags:{
                black:true,
                plain:true,
            }
        },
        sunglasses05:{
            masterItem:"sunglasses",
            variant:"sunglasses_05",
            name:"Aviator Sunglasses with Grey Lenses",
            price:20,
            daring:0,
            disabled:false,
            isMale:true,
            isFemale:true,
            isItemSet:false,
            setName:"",
            tags:{
                grey:true,
                plain:true,
            }
        },
        sunglasses06:{
            masterItem:"sunglasses",
            variant:"sunglasses_06",
            name:"Metal Framed Sunglasses with Yellow Lenses",
            price:20,
            daring:0,
            disabled:false,
            isMale:true,
            isFemale:true,
            isItemSet:false,
            setName:"",
            tags:{
                yellow:true,
                plain:true,
            }
        },
        sunglasses07:{
            masterItem:"sunglasses",
            variant:"sunglasses_07",            
            name:"Tortoise Brown Ladies Sunglasses",
            price:20,
            daring:0,
            disabled:false,
            isMale:false,
            isFemale:true,
            isItemSet:false,
            setName:"",
            tags:{
                brown:true,
                plain:true,
            }
        },
        sunglasses08:{
            masterItem:"sunglasses",
            variant:"sunglasses_08",
            name:"Tortise Red Ladies Sunglasses with Gold Trim",
            price:20,
            daring:0,
            disabled:false,
            isMale:false,
            isFemale:true,
            isItemSet:false,
            setName:"",
            tags:{
                red:true,
                plain:true,
            }
        },
        sunglasses09:{
            masterItem:"sunglasses",
            variant:"sunglasses_09",
            name:"Black Sunglasses with Blue Highlights",
            price:20,
            daring:0,
            disabled:false,
            isMale:true,
            isFemale:true,
            isItemSet:false,
            setName:"",
            tags:{
                black:true,
                plain:true,
            }
        },
        sunglasses10:{
            masterItem:"sunglasses",
            variant:"sunglasses_10",
            name:"Red Ladies Sunglasses",
            price:20,
            daring:0,
            disabled:false,
            isMale:false,
            isFemale:true,
            isItemSet:false,
            setName:"",
            tags:{
                red:true,
                plain:true,
            }
        },
        sunglasses11:{
            masterItem:"sunglasses",
            variant:"sunglasses_11",
            name:"Tortise Brown Ladies Sunglasses with Wide Arms",
            price:20,
            daring:0,
            disabled:false,
            isMale:false,
            isFemale:true,
            isItemSet:false,
            setName:"",
            tags:{
                brown:true,
                plain:true,
            }
        },

        //glasses
        glasses00:{
            masterItem:"glasses",
            variant:"glasses_00",
            name:"Round Frame Harry Potter Glasses",
            price:20,
            daring:0,
            disabled:false,
            isMale:true,
            isFemale:true,
            isItemSet:false,
            setName:"",
            tags:{
                plain:true,
            }
        },
        glasses01:{
            masterItem:"glasses",
            variant:"glasses_01",
            name:"Black Frame Librarian Glasses",
            price:20,
            daring:0,
            disabled:false,
            isMale:false,
            isFemale:true,
            isItemSet:false,
            setName:"",
            tags:{
                black:true,
                plain:true,
            }
        },
        glasses02:{
            masterItem:"glasses",
            variant:"glasses_02",
            name:"Gold Round Frame Harry Potter Glasses",
            price:20,
            daring:0,
            disabled:false,
            isMale:true,
            isFemale:true,
            isItemSet:false,
            setName:"",
            tags:{
                plain:true,
            }
        },
        glasses03:{
            masterItem:"glasses",
            variant:"glasses_03",
            name:"Black Framed Glasses",
            price:20,
            daring:0,
            disabled:false,
            isMale:true,
            isFemale:true,
            isItemSet:false,
            setName:"",
            tags:{
                black:true,
                plain:true,
            }
        },
        glasses04:{
            masterItem:"glasses",
            variant:"glasses_04",
            name:"Black Framed Ladies Glasses",
            price:20,
            daring:0,
            disabled:false,
            isMale:false,
            isFemale:true,
            isItemSet:false,
            setName:"",
            tags:{
                black:true,
                plain:true,
            }
        },
        glasses05:{
            masterItem:"glasses",
            variant:"glasses_05",
            name:"Pink Framed Ladies Glasses",
            price:20,
            daring:0,
            disabled:false,
            isMale:false,
            isFemale:true,
            isItemSet:false,
            setName:"",
            tags:{
                pink:true,
                plain:true,
            }
        },
        glasses06:{
            masterItem:"glasses",
            variant:"glasses_06",
            name:"Tortoise Brown Ladies Glasses",
            price:20,
            daring:0,
            disabled:false,
            isMale:false,
            isFemale:true,
            isItemSet:false,
            setName:"",
            tags:{
                brown:true,
                plain:true,
            }
        },
        glasses07:{
            masterItem:"glasses",
            variant:"glasses_07",
            name:"Thin Black Framed Ladies Glasses",
            price:20,
            daring:0,
            disabled:false,
            isMale:false,
            isFemale:true,
            isItemSet:false,
            setName:"",
            tags:{
                black:true,
                plain:true,
            }
        },
        glasses08:{
            masterItem:"glasses",
            variant:"glasses_08",
            name:"Blue Framed Ladies Glasses",
            price:20,
            daring:0,
            disabled:false,
            isMale:false,
            isFemale:true,
            isItemSet:false,
            setName:"",
            tags:{
                blue:true,
                plain:true,
            }
        },
        glasses09:{
            masterItem:"glasses",
            variant:"glasses_09",
            name:"Pink Framed Librarian Glasses",
            price:20,
            daring:0,
            disabled:false,
            isMale:false,
            isFemale:true,
            isItemSet:false,
            setName:"",
            tags:{
                pink:true,
                plain:true,
            }
        },

        //blindfold
        blindfold00:{
            masterItem:"blindfold",
            variant:"blindfold_00",
            name:"Black Leather Blindfold",
            price:20,
            daring:0,
            disabled:false,
            isMale:true,
            isFemale:true,
            isItemSet:false,
            setName:"",
            tags:{
                black:true,
                plain:true,
            }
        },
        blindfold01:{
            masterItem:"blindfold",
            variant:"blindfold_01",
            name:"Red Suede Blindfold",
            price:20,
            daring:0,
            disabled:false,
            isMale:true,
            isFemale:true,
            isItemSet:false,
            setName:"",
            tags:{
                red:true,
                plain:true,
            }
        },
        blindfold02:{
            masterItem:"blindfold",
            variant:"blindfold_02",
            name:"Red Sleep Mask Blindfold",
            price:20,
            daring:0,
            disabled:false,
            isMale:true,
            isFemale:true,
            isItemSet:false,
            setName:"",
            tags:{
                red:true,
                plain:true,
            }
        },
        blindfold03:{
            masterItem:"blindfold",
            variant:"blindfold_03",
            name:"Black Leather Blindfold with Nose Mould",
            price:20,
            daring:0,
            disabled:false,
            isMale:true,
            isFemale:true,
            isItemSet:false,
            setName:"",
            tags:{
                black:true,
                plain:true,
            }
        },    
    }
});