if(typeof window.items == "undefined"){
    window.items = {};
}

$.extend(true, window.items, {
    itemMasters:{
        //Mouthpeices
        gag:{
            itemType:"mouthpeice",
            clothingSlot:"mouth",
            name:"Gags",
            itemMaster: "gag",
            daring:0,
            disabled:false,
            hasWorn:false,
            isMale:true,
            isFemale:true,
            tags:{
                plain:true,
            }
        },    
    },
    itemChildren:{
        //gag
        gag_00:{
            masterItem:"gag",
            variant:"gag_00",
            name:"Black Leather Ball Gag",
            price:20,
            daring:0,
            disabled:false,
            isMale:true,
            isFemale:true,
            isItemSet:false,
            setName:"",
            canBuy:true,
            tags:{
                black:true,
                sexy:true,
                slutty:true,
            }
        },
        gag_01:{
            masterItem:"gag",
            variant:"gag_01",
            name:"Black Leather Ring Gag",
            price:20,
            daring:0,
            disabled:false,
            isMale:true,
            isFemale:true,
            isItemSet:false,
            setName:"",
            canBuy:true,
            tags:{
                black:true,
                sexy:true,
                slutty:true,
            }
        },
        gag_02:{
            masterItem:"gag",
            variant:"gag_02",
            name:"Black Leather Anal Bead Gag",
            price:20,
            daring:0,
            disabled:false,
            isMale:true,
            isFemale:true,
            isItemSet:false,
            setName:"",
            canBuy:true,
            tags:{
                black:true,
                sexy:true,
                slutty:true,
            }
        },
        gag_03:{
            masterItem:"gag",
            variant:"gag_03",
            name:"Black Leather Lips Gag",
            price:20,
            daring:0,
            disabled:false,
            isMale:true,
            isFemale:true,
            isItemSet:false,
            setName:"",
            canBuy:true,
            tags:{
                black:true,
                sexy:true,
                slutty:true,
            }
        },
        gag_04:{
            masterItem:"gag",
            variant:"gag_04",
            name:"Black Leather Dildo Gag",
            price:20,
            daring:0,
            disabled:false,
            isMale:true,
            isFemale:true,
            isItemSet:false,
            setName:"",
            canBuy:true,
            tags:{
                black:true,
                sexy:true,
                slutty:true,
            }
        },
        gag_05:{
            masterItem:"gag",
            variant:"gag_05",
            name:"Black Leather Dog Bone Gag",
            price:20,
            daring:0,
            disabled:false,
            isMale:true,
            isFemale:true,
            isItemSet:false,
            setName:"",
            canBuy:true,
            tags:{
                black:true,
                sexy:true,
                slutty:true,
            }
        },
        gag_06:{
            masterItem:"gag",
            variant:"gag_06",
            name:"Black Leather Metal Hook Gag",
            price:20,
            daring:0,
            disabled:false,
            isMale:true,
            isFemale:true,
            isItemSet:false,
            setName:"",
            canBuy:true,
            tags:{
                black:true,
                sexy:true,
                slutty:true,
            }
        },
        gag_07:{
            masterItem:"gag",
            variant:"gag_07",
            name:"Red and Black Leather Ring Gag",
            price:20,
            daring:0,
            disabled:false,
            isMale:true,
            isFemale:true,
            isItemSet:false,
            setName:"",
            canBuy:true,
            tags:{
                black:true,
                red:true,
                sexy:true,
                slutty:true,
            }
        },
        gag_08:{
            masterItem:"gag",
            variant:"gag_08",
            name:"Black Leather Gasmask Gag",
            price:20,
            daring:0,
            disabled:false,
            isMale:true,
            isFemale:true,
            isItemSet:false,
            setName:"",
            canBuy:true,
            tags:{
                black:true,
                sexy:true,
                slutty:true,
            }
        },
        gag_09:{
            masterItem:"gag",
            variant:"gag_09",
            name:"Black Leather Cock Gag",
            price:20,
            daring:0,
            disabled:false,
            isMale:true,
            isFemale:true,
            isItemSet:false,
            setName:"",
            canBuy:true,
            tags:{
                black:true,
                sexy:true,
                slutty:true,
				maid:true,
            }
        },
        gag_10:{
            masterItem:"gag",
            variant:"gag_10",
            name:"Black Leather Inflatable Gag",
            price:20,
            daring:0,
            disabled:false,
            isMale:true,
            isFemale:true,
            isItemSet:false,
            setName:"",
            canBuy:true,
            tags:{
                black:true,
                sexy:true,
                slutty:true,
            }
        },    
    }
});