if(typeof window.items == "undefined"){
    window.items = {};
}

$.extend(true, window.items, {
    itemMasters:{
        //Tatoos
        lamps:{
            itemType:"roomItems",
            clothingSlot:"lamps",
            name:"Lamps",
            daring:0,
            disabled:false,
            hasWorn:false,
            isMale:true,
            isFemale:true,
            tags:{
                room:true,
            }
        },
        rooms:{
            itemType:"roomItems",
            clothingSlot:"lamps",
            name:"Room Decorations",
            daring:0,
            disabled:false,
            hasWorn:false,
            isMale:true,
            isFemale:true,
            tags:{
                room:true,
            }
        }
    },
    itemChildren:{
        lamp0:{
            masterItem:"lamps",
            variant:"lamp_classic",
            name:"Classic Lamp",
            price:20,
            daring:0,
            disabled:false,
            isMale:true,
            isFemale:true,
            isItemSet:false,
            setName:"",
            tags:{
                room:true
            }
        },
        lamp1:{
            masterItem:"lamps",
            variant:"lamp_purple",
            name:"Purple Lamp",
            price:35,
            daring:0,
            disabled:false,
            isMale:true,
            isFemale:true,
            isItemSet:false,
            setName:"",
            tags:{
                room:true
            }
        },
        lamp2:{
            masterItem:"lamps",
            variant:"lamp_tube",
            name:"Tube Lamp",
            price:25,
            daring:0,
            disabled:false,
            isMale:true,
            isFemale:true,
            isItemSet:false,
            setName:"",
            tags:{
                room:true
            }
        },

        room0:{
            masterItem:"rooms",
            variant:"room_gamer",
            name:"Video Game Themed Decorations",
            price:100,
            daring:0,
            disabled:false,
            isMale:true,
            isFemale:false,
            isItemSet:false,
            setName:"room_gamer",
            tags:{
                room:true
            }
        },
        room1:{
            masterItem:"rooms",
            variant:"room_gamer_girl",
            name:"Video Game Themed Decorations",
            price:100,
            daring:0,
            disabled:true,
            isMale:false,
            isFemale:true,
            isItemSet:false,
            setName:"room_gamer",
            tags:{
                room:true
            }
        },
        room2:{
            masterItem:"rooms",
            variant:"room_geek",
            name:"Fantasy Themed Decorations",
            price:120,
            daring:0,
            disabled:false,
            isMale:true,
            isFemale:false,
            isItemSet:false,
            setName:"room_geek",
            tags:{
                room:true
            }
        },
        room3:{
            masterItem:"rooms",
            variant:"room_geek_girl",
            name:"Fantasy Themed Decorations",
            price:120,
            daring:0,
            disabled:true,
            isMale:false,
            isFemale:true,
            isItemSet:false,
            setName:"room_geek",
            tags:{
                room:true
            }
        },
        room4:{
            masterItem:"rooms",
            variant:"room_punk",
            name:"Various Punky Decorations",
            price:80,
            daring:0,
            disabled:false,
            isMale:true,
            isFemale:false,
            isItemSet:false,
            setName:"room_punk",
            tags:{
                room:true
            }
        },
        room5:{
            masterItem:"rooms",
            variant:"room_punk_girl",
            name:"Various Punky Decorations",
            price:80,
            daring:0,
            disabled:true,
            isMale:false,
            isFemale:true,
            isItemSet:false,
            setName:"room_punk",
            tags:{
                room:true
            }
        },
        room6:{
            masterItem:"rooms",
            variant:"room_sport",
            name:"Sport Themed Decorations",
            price:90,
            daring:0,
            disabled:false,
            isMale:true,
            isFemale:false,
            isItemSet:false,
            setName:"room_sport",
            tags:{
                room:true
            }
        },
        room7:{
            masterItem:"rooms",
            variant:"room_sport_girl",
            name:"Sport Themed Decorations",
            price:90,
            daring:0,
            disabled:true,
            isMale:false,
            isFemale:true,
            isItemSet:false,
            setName:"room_sport",
            tags:{
                room:true
            }
        },
        room8:{
            masterItem:"rooms",
            variant:"room_girly_girl",
            name:"Girly Girl Room Decorations",
            price:0,
            daring:0,
            disabled:true,
            isMale:false,
            isFemale:true,
            isItemSet:false,
            setName:"",
            tags:{
                room:true
            }
        },
    }
});
