if(typeof window.items == "undefined"){
    window.items = {};
}

$.extend(true, window.items, {
    itemMasters:{
        //Tattoos
        tattoos:{
            itemType:"tattoos",
            clothingSlot:"",
            name:"Tattoos",
            itemMaster: "tattoos",
            daring:8,
            disabled:false,
            hasWorn:false,
            isMale:true,
            isFemale:true,
            tags:{
                plain:true,
            }
        },
    },
    itemChildren:{
        tattoo00:{
            masterItem:"tattoos",
            variant:"tattoo_bunny",
            name:"Bunny Tattoo",
            price:20,
            daring:7,
            disabled:false,
            isMale:true,
            isFemale:true,
            isItemSet:false,
            setName:"",
            canBuy:true,
            tags:{
                plain:true,
                pink:true,
                tattoo:true,
            }
        },
        tattoo01:{
            masterItem:"tattoos",
            variant:"tattoo_butterfly",
            name:"Butterfly Tattoo",
            price:100,
            daring:7,
            disabled:false,
            isMale:true,
            isFemale:true,
            isItemSet:false,
            setName:"",
            canBuy:true,
            tags:{
                plain:true,
                pink:true,
                tattoo:true,
            }
        },
        tattoo02:{
            masterItem:"tattoos",
            variant:"tattoo_heart",
            name:"Heart Tattoo",
            price:15,
            daring:8,
            disabled:false,
            isMale:true,
            isFemale:true,
            isItemSet:false,
            setName:"",
            canBuy:true,
            tags:{
                plain:true,
                pink:true,
                tattoo:true,
            }
        },
        tattoo03:{
            masterItem:"tattoos",
            variant:"tattoo_sissy",
            name:"Sissy Tattoo",
            price:10,
            daring:8,
            disabled:false,
            isMale:true,
            isFemale:true,
            isItemSet:false,
            setName:"",
            canBuy:true,
            tags:{
                plain:true,
                tattoo:true,
            }
        },
        tattoo04:{
            masterItem:"tattoos",
            variant:"tattoo_slut",
            name:"Slut Tattoo",
            price:60,
            daring:8,
            disabled:false,
            isMale:true,
            isFemale:true,
            isItemSet:false,
            setName:"",
            canBuy:true,
            tags:{
                plain:true,
                tattoo:true,
            }
        },
        tattoo05:{
            masterItem:"tattoos",
            variant:"tattoo_stockings",
            name:"Stockings Tattoo",
            price:80,
            daring:7,
            disabled:false,
            isMale:true,
            isFemale:true,
            isItemSet:false,
            setName:"",
            canBuy:true,
            tags:{
                plain:true,
                tattoo:true,
            }
        },
        tattoo06:{
            masterItem:"tattoos",
            variant:"tattoo_stupidwhore",
            name:"Stupid Whore Tattoo",
            price:40,
            daring:8,
            disabled:false,
            isMale:true,
            isFemale:true,
            isItemSet:false,
            setName:"",
            canBuy:true,
            tags:{
                plain:true,
                tattoo:true,
            }
        },
        tattoo07:{
            masterItem:"tattoos",
            variant:"beauty_mark",
            name:"Beauty Mark",
            price:10,
            daring:7,
            disabled:false,
            isMale:true,
            isFemale:true,
            isItemSet:false,
            setName:"",
            canBuy:true,
            tags:{
                plain:true,
                tattoo:true,
            }
        },
    }
});