if(typeof window.items == "undefined"){
    window.items = {};
}

$.extend(true, window.items, {
    itemMasters:{
        //Tatoos
        tattoos:{
            itemType:"tattoos",
            clothingSlot:"",
            name:"Tattoos",
            itemMaster: "tattoos",
            daring:8,
            disabled:false,
            hasWorn:false,
            isMale:true,
            isFemale:true,
            tags:{
                plain:true,
            }
        },
    },
    itemChildren:{
        tattoo0:{
            masterItem:"tattoos",
            variant:"tattoo_bunny",
            name:"Bunny Tattoo",
            price:20,
            daring:7,
            disabled:false,
            isMale:true,
            isFemale:true,
            isItemSet:false,
            setName:"",
            tags:{
                plain:true,
                pink:true,
                tattoo:true,
            }
        },
        tattoo1:{
            masterItem:"tattoos",
            variant:"tattoo_butterfly",
            name:"Butterfly Tattoo",
            price:100,
            daring:7,
            disabled:false,
            isMale:true,
            isFemale:true,
            isItemSet:false,
            setName:"",
            tags:{
                plain:true,
                pink:true,
                tattoo:true,
            }
        },
        tattoo2:{
            masterItem:"tattoos",
            variant:"tattoo_heart",
            name:"Heart Tattoo",
            price:15,
            daring:8,
            disabled:false,
            isMale:true,
            isFemale:true,
            isItemSet:false,
            setName:"",
            tags:{
                plain:true,
                pink:true,
                tattoo:true,
            }
        },
        tattoo3:{
            masterItem:"tattoos",
            variant:"tattoo_sissy",
            name:"Sissy Tattoo",
            price:10,
            daring:8,
            disabled:false,
            isMale:true,
            isFemale:true,
            isItemSet:false,
            setName:"",
            tags:{
                plain:true,
                tattoo:true,
            }
        },
        tattoo4:{
            masterItem:"tattoos",
            variant:"tattoo_slut",
            name:"Slut Tattoo",
            price:60,
            daring:8,
            disabled:false,
            isMale:true,
            isFemale:true,
            isItemSet:false,
            setName:"",
            tags:{
                plain:true,
                tattoo:true,
            }
        },
        tattoo5:{
            masterItem:"tattoos",
            variant:"tattoo_stockings",
            name:"Stockings Tattoo",
            price:80,
            daring:7,
            disabled:false,
            isMale:true,
            isFemale:true,
            isItemSet:false,
            setName:"",
            tags:{
                plain:true,
                tattoo:true,
            }
        },
        tattoo6:{
            masterItem:"tattoos",
            variant:"tattoo_stupidwhore",
            name:"Stupid Whore Tattoo",
            price:40,
            daring:8,
            disabled:false,
            isMale:true,
            isFemale:true,
            isItemSet:false,
            setName:"",
            tags:{
                plain:true,
                tattoo:true,
            }
        },
        tattoo6:{
            masterItem:"tattoos",
            variant:"beauty_mark",
            name:"Beauty Mark",
            price:10,
            daring:7,
            disabled:false,
            isMale:true,
            isFemale:true,
            isItemSet:false,
            setName:"",
            tags:{
                plain:true,
                tattoo:true,
            }
        },
    }
});