//Macros


//JS Functions
window.itemFuncs= {
    hasTag: function(item, tag){
        var locItem = window.items.itemChildren[item];
        if(!(locItem === undefined)){
            if(!(locItem.tags[tag] === undefined)){
                return locItem.tags[tag];
            }
            else{
                var masterItem = window.items.itemMasters[locItem.masterItem];
                if(!(masterItem.tags[tag] === undefined)){
                    return masterItem.tags[tag];
                }
                else{
                    return false;
                }
            }
        }
        else{
            return false;
        }
    },
    notTag: function (item, tag){
        var locItem = window.items.itemChildren[item];
        if(!(locItem === undefined)){
            if(!(locItem.tags[tag] === undefined)){
                return false;
            }
            else{
                var masterItem = window.items.itemMasters[locItem.masterItem];
                if(!(masterItem.tags[tag] === undefined)){
                    return false;
                }
                else{
                    return true;
                }
            }
        }
        else{
            return false;
        }
    },
    hasTagsAnd: function (item, tags){
        var hasTags = false;
        if(tags.constructor === Array){
            hasTags = true;
            for(var i = 0; i < tags.length && hasTags === true; i++){
                var hasTag = window.itemFuncs.hasTag(item, tags[i]);
                hasTags = hasTag;
            }
        }
        return hasTags;
    },
    hasTagsOr: function (item, tags){
        var hasTags = false;
        if(tags.constructor === Array){
            for(var i = 0; i < tags.length; i++){
                var hasTag = window.itemFuncs.hasTag(item, tags[i]);
                if(hasTag){
                    hasTags = hasTag;
                    break;
                }
            }
        }
        return hasTags;
    },
    notTagsAnd: function (item, tags){
        var notTags = false;
        if(tags.constructor === Array){
            notTags = true;
            for(var i = 0; i < tags.length && notTags === true; i++){
                var notTag = window.itemFuncs.notTag(item, tags[i]);
                notTags = notTag;
            }
        }
        return notTags;
    },
    notTagsOr: function (item, tags){
        var notTags = false;
        if(tags.constructor === Array){
            for(var i = 0; i < tags.length; i++){
                var notTag = window.itemFuncs.notTag(item, tags[i]);
                if(notTag){
                    notTags = notTag;
                    break;
                }
            }
        }
        return notTags;
    },

}

// NotClothing:   0,
// Underwear:     1,
// Outerwear:     2,
// Shoes:         4,
// Bras:          8,
// Chastity:     16,
// AnalPlug:     32,
// Stockings:    64,
// Earrings:    128,
// Collar:      256,
// Extra:       512,
// Hairband:   1024

//Objects
window.items={
    itemMasters:{
        //Underwear
        boxers:{
            itemType:"underwear",
            clothingSlot:"underwear",
            daring:0,
            disabled:false,
            hasWorn:false,
            isMale:true,
            isFemale:false,
            tags:{
                plain:true,
                
            }
        },
        plainPanties:{
            itemType:"underwear",
            clothingSlot:"underwear",
            daring:3,
            disabled:false,
            hasWorn:false,
            isMale:true,
            isFemale:false,
            tags:{
                plain:true,
                
            }
        },
        sexyPanties:{
            itemType:"underwear",
            clothingSlot:"underwear",
            daring:3,
            disabled:false,
            hasWorn:false,
            isMale:false,
            isFemale:true,
            tags:{
                sexy:true,
                
            }
        },
        latexPanties:{
            itemType:"underwear",
            clothingSlot:"underwear",
            daring:5,
            disabled:false,
            hasWorn:false,
            isMale:false,
            isFemale:true,
            tags:{
                sexy:true,
                slutty:true,
            }
        },

        //Outerwear
        tshirtJeans:{
            itemType:"outerwear",
            clothingSlot:"outerwear",
            daring:0,
            disabled:false,
            hasWorn:false,
            isMale:true,
            isFemale:false,
            tags:{
                plain:true,
                
            }
        },
        skirtTop:{
            itemType:"outerwear",
            clothingSlot:"outerwear",
            daring:5,
            disabled:false,
            hasWorn:false,
            isMale:false,
            isFemale:true,
            tags:{
                plain:true,
                
            }
        },
        casualDress:{
            itemType:"outerwear",
            clothingSlot:"outerwear",
            daring:5,
            disabled:false,
            hasWorn:false,
            isMale:false,
            isFemale:true,
            tags:{
                plain:true,
                
            }
        },
        sluttyDress:{
            itemType:"outerwear",
            clothingSlot:"outerwear",
            daring:7,
            disabled:false,
            hasWorn:false,
            isMale:false,
            isFemale:true,
            tags:{
                sexy:true,
                slutty:true,
            }
        },

        //Shoes


        shoes:{

        },
        bras:{

        },
        chastity:{

        },
        analplug:{

        },
        stockings:{

        },
        earrings:{

        },
        collar:{

        },
        extra:{

        },
        hairband:{

        }
    },
    itemChildren:{
        //Boxers
        luckyBoxers0:{
            masterItem:"boxers",
            variant:"lucky_jocks_00",
            price:10,
            daring:0,
            disabled:false,
            isMale:true,
            isFemale:false,
            tags:{
                plain:true,
                grey:true,
                school:true,
            }
        },
        luckyBoxers1:{
            masterItem:"boxers",
            variant:"lucky_jocks_01",
            price:10,
            daring:0,
            disabled:false,
            isMale:true,
            isFemale:false,
            tags:{
                plain:true,
                blue:true,
                school:true,
            }
        },
        luckyBoxers2:{
            masterItem:"boxers",
            variant:"lucky_jocks_02",
            price:10,
            daring:0,
            disabled:false,
            isMale:true,
            isFemale:false,
            tags:{
                plain:true,
                yellow:true,
                school:true,
            }
        },
        luckyBoxers3:{
            masterItem:"boxers",
            variant:"lucky_jocks_03",
            price:10,
            daring:0,
            disabled:false,
            isMale:true,
            isFemale:false,
            tags:{
                plain:true,
                grey:true,
                school:true,
            }
        },
        luckyBoxers4:{
            masterItem:"boxers",
            variant:"lucky_jocks_04",
            price:10,
            daring:0,
            disabled:false,
            isMale:true,
            isFemale:false,
            tags:{
                plain:true,
                black:true,
                school:true,
            }
        },
        luckyBoxers5:{
            masterItem:"boxers",
            variant:"lucky_jocks_05",
            price:10,
            daring:0,
            disabled:false,
            isMale:true,
            isFemale:false,
            tags:{
                plain:true,
                grey:true,
                school:true,
            }
        },
        luckyBoxers6:{
            masterItem:"boxers",
            variant:"lucky_jocks_06",
            price:10,
            daring:0,
            disabled:false,
            isMale:true,
            isFemale:false,
            tags:{
                plain:true,
                grey:true,
                yellow:true,
                school:true,
            }
        },
        luckyBoxers7:{
            masterItem:"boxers",
            variant:"lucky_jocks_07",
            price:10,
            daring:0,
            disabled:false,
            isMale:true,
            isFemale:false,
            tags:{
                plain:true,
                red:true,
                school:true,
            }
        },

        //Plain Panties
        cottonPanties0:{
            masterItem:"plainPanties",
            variant:"panties_cotton_00",
            price:15,
            daring:3,
            disabled:false,
            isMale:false,
            isFemale:true,
            tags:{
                plain:true,
                white:true,
                school:true,

            }
        },
        cottonPanties1:{
            masterItem:"plainPanties",
            variant:"panties_cotton_01",
            price:15,
            daring:3,
            disabled:false,
            isMale:false,
            isFemale:true,
            tags:{
                plain:true,
                white:true,
                school:true,
                
            }
        },
        cottonPanties2:{
            masterItem:"plainPanties",
            variant:"panties_cotton_02",
            price:15,
            daring:3,
            disabled:false,
            isMale:false,
            isFemale:true,
            tags:{
                plain:true,
                white:true,
                school:true,
                frilly:true,
            }
        },
        cottonPanties3:{
            masterItem:"plainPanties",
            variant:"panties_cotton_03",
            price:15,
            daring:3,
            disabled:false,
            isMale:false,
            isFemale:true,
            tags:{
                plain:true,
                white:true,
                school:true,
                polkadot:true,
                frilly:true,
            }
        },
        cottonPanties4:{
            masterItem:"plainPanties",
            variant:"panties_cotton_04",
            price:15,
            daring:3,
            disabled:false,
            isMale:false,
            isFemale:true,
            tags:{
                plain:true,
                pink:true,
                school:true,
                
            }
        },
        cottonPanties5:{
            masterItem:"plainPanties",
            variant:"panties_cotton_05",
            price:15,
            daring:3,
            disabled:false,
            isMale:false,
            isFemale:true,
            tags:{
                plain:true,
                pink:true,
                school:true,
                striped:true,
            }
        },
        cottonPanties6:{
            masterItem:"plainPanties",
            variant:"panties_cotton_06",
            price:15,
            daring:3,
            disabled:false,
            isMale:false,
            isFemale:true,
            tags:{
                plain:true,
                pink:true,
                school:true,
                
            }
        },
        cottonPanties7:{
            masterItem:"plainPanties",
            variant:"panties_cotton_07",
            price:15,
            daring:3,
            disabled:false,
            isMale:false,
            isFemale:true,
            tags:{
                plain:true,
                grey:true,
                school:true,
                
            }
        },
        cottonPanties8:{
            masterItem:"plainPanties",
            variant:"panties_cotton_40",
            price:15,
            daring:3,
            disabled:false,
            isMale:false,
            isFemale:true,
            tags:{
                plain:true,
                black:true,
                white:true,
                school:true,
                polkadot:true,
                boyshort:true,
                
            }
        },
        cottonPanties9:{
            masterItem:"plainPanties",
            variant:"panties_cotton_60",
            price:15,
            daring:3,
            disabled:false,
            isMale:false,
            isFemale:true,
            tags:{
                plain:true,
                blue:true,
                school:true,
                frilly:true,
            }
        },

        //Sexy Panties
        sexyPanties0:{
            masterItem:"sexyPanties",
            variant:"panties_sexy_00",
            price:55,
            daring:3,
            disabled:false,
            isMale:false,
            isFemale:true,
            tags:{
                sexy:true,
                red:true,
                school:true,
                
            }
        },
        sexyPanties1:{
            masterItem:"sexyPanties",
            variant:"panties_sexy_01",
            price:55,
            daring:3,
            disabled:false,
            isMale:false,
            isFemale:true,
            tags:{
                sexy:true,
                red:true,
                school:true,
                
            }
        },
        sexyPanties2:{
            masterItem:"sexyPanties",
            variant:"panties_sexy_02",
            price:55,
            daring:3,
            disabled:false,
            isMale:false,
            isFemale:true,
            tags:{
                sexy:true,
                pink:true,
                school:true,
                
            }
        },
        sexyPanties3:{
            masterItem:"sexyPanties",
            variant:"panties_sexy_03",
            price:55,
            daring:3,
            disabled:false,
            isMale:false,
            isFemale:true,
            tags:{
                sexy:true,
                pink:true,
                black:true,
                school:true,
                frilly:true,
            }
        },
        sexyPanties4:{
            masterItem:"sexyPanties",
            variant:"panties_sexy_04",
            price:55,
            daring:3,
            disabled:false,
            isMale:false,
            isFemale:true,
            tags:{
                sexy:true,
                blue:true,
                school:true,
                frilly:true,
            }
        },
        sexyPanties5:{
            masterItem:"sexyPanties",
            variant:"panties_sexy_05",
            price:55,
            daring:3,
            disabled:false,
            isMale:false,
            isFemale:true,
            tags:{
                sexy:true,
                pink:true,
                school:true,
                frilly:true,
            }
        },
        sexyPanties6:{
            masterItem:"sexyPanties",
            variant:"panties_sexy_06",
            price:55,
            daring:3,
            disabled:false,
            isMale:false,
            isFemale:true,
            tags:{
                sexy:true,
                purple:true,
                school:true,
                frilly:true,
            }
        },
        sexyPanties7:{
            masterItem:"sexyPanties",
            variant:"panties_sexy_07",
            price:55,
            daring:3,
            disabled:false,
            isMale:false,
            isFemale:true,
            tags:{
                sexy:true,
                pink:true,
                school:true,
                frilly:true,
                gstring:true,
            }
        },
        sexyPanties8:{
            masterItem:"sexyPanties",
            variant:"panties_sexy_08",
            price:55,
            daring:3,
            disabled:false,
            isMale:false,
            isFemale:true,
            tags:{
                sexy:true,
                yellow:true,
                school:true,
                frilly:true,
            }
        },
        sexyPanties9:{
            masterItem:"sexyPanties",
            variant:"panties_sexy_09",
            price:55,
            daring:3,
            disabled:false,
            isMale:false,
            isFemale:true,
            tags:{
                sexy:true,
                purple:true,
                school:true,
                frilly:true,
                gstring:true,
            }
        },
        sexyPanties10:{
            masterItem:"sexyPanties",
            variant:"panties_sexy_10",
            price:55,
            daring:3,
            disabled:false,
            isMale:false,
            isFemale:true,
            tags:{
                sexy:true,
                purple:true,
                school:true,
                frilly:true,
                gstring:true
            }
        },
        sexyPanties11:{
            masterItem:"sexyPanties",
            variant:"panties_sexy_11",
            price:55,
            daring:3,
            disabled:false,
            isMale:false,
            isFemale:true,
            tags:{
                sexy:true,
                pink:true,
                school:true,
                frilly:true,
            }
        },
        sexyPanties12:{
            masterItem:"sexyPanties",
            variant:"panties_sexy_12",
            price:55,
            daring:3,
            disabled:false,
            isMale:false,
            isFemale:true,
            tags:{
                sexy:true,
                blue:true,
                black:true,
                school:true,
                
            }
        },
        sexyPanties13:{
            masterItem:"sexyPanties",
            variant:"panties_sexy_13",
            price:55,
            daring:3,
            disabled:false,
            isMale:false,
            isFemale:true,
            tags:{
                sexy:true,
                blue:true,
                school:true,
                frilly:true,
            }
        },
        sexyPanties14:{
            masterItem:"sexyPanties",
            variant:"panties_sexy_14",
            price:55,
            daring:3,
            disabled:false,
            isMale:false,
            isFemale:true,
            tags:{
                sexy:true,
                black:true,
                school:true,
                frilly:true,
                gstring:true
            }
        },
        sexyPanties15:{
            masterItem:"sexyPanties",
            variant:"panties_sexy_15",
            price:55,
            daring:3,
            disabled:false,
            isMale:false,
            isFemale:true,
            tags:{
                sexy:true,
                black:true,
                school:true,
                frilly:true,
                gstring:true
            }
        },
        sexyPanties16:{
            masterItem:"sexyPanties",
            variant:"panties_sexy_16",
            price:55,
            daring:3,
            disabled:false,
            isMale:false,
            isFemale:true,
            tags:{
                sexy:true,
                black:true,
                school:true,
                frilly:true,
                gstring:true
            }
        },
        sexyPanties17:{
            masterItem:"sexyPanties",
            variant:"panties_sexy_17",
            price:55,
            daring:3,
            disabled:false,
            isMale:false,
            isFemale:true,
            tags:{
                sexy:true,
                white:true,
                school:true,
                frilly:true,
                gstring:true
            }
        },
        sexyPanties18:{
            masterItem:"sexyPanties",
            variant:"panties_sexy_18",
            price:55,
            daring:3,
            disabled:false,
            isMale:false,
            isFemale:true,
            tags:{
                sexy:true,
                red:true,
                school:true,
                frilly:true,
                gstring:true
            }
        },
        sexyPanties19:{
            masterItem:"sexyPanties",
            variant:"panties_sexy_40",
            price:55,
            daring:3,
            disabled:false,
            isMale:false,
            isFemale:true,
            tags:{
                sexy:true,
                black:true,
                school:true,
                frilly:true,
                gstring:true
            }
        },
        sexyPanties20:{
            masterItem:"sexyPanties",
            variant:"panties_sexy_41",
            price:55,
            daring:3,
            disabled:false,
            isMale:false,
            isFemale:true,
            tags:{
                sexy:true,
                red:true,
                school:true,
                frilly:true,
                gstring:true
            }
        },
        sexyPanties21:{
            masterItem:"sexyPanties",
            variant:"panties_sexy_60",
            price:55,
            daring:3,
            disabled:false,
            isMale:false,
            isFemale:true,
            tags:{
                sexy:true,
                pink:true,
                school:true,
                frilly:true,
                gstring:true
            }
        },

        //Latex Panties
        latexPanties0:{
            masterItem:"latexPanties",
            variant:"panties_latex_00",
            price:80,
            daring:5,
            disabled:false,
            isMale:false,
            isFemale:true,
            tags:{
                sexy:true,
                slutty:true,
                black:true,
                school:true,
            }
        },
        latexPanties1:{
            masterItem:"latexPanties",
            variant:"panties_latex_01",
            price:80,
            daring:5,
            disabled:false,
            isMale:false,
            isFemale:true,
            tags:{
                sexy:true,
                slutty:true,
                black:true,
                school:true,
            }
        },
        latexPanties2:{
            masterItem:"latexPanties",
            variant:"panties_latex_02",
            price:80,
            daring:5,
            disabled:false,
            isMale:false,
            isFemale:true,
            tags:{
                sexy:true,
                slutty:true,
                black:true,
                school:true,
                gstring:true,
            }
        },
        latexPanties3:{
            masterItem:"latexPanties",
            variant:"panties_latex_40",
            price:80,
            daring:5,
            disabled:false,
            isMale:false,
            isFemale:true,
            tags:{
                sexy:true,
                slutty:true,
                pink:true,
                school:true,
            }
        },

        //Tshirt Jeans
        tshirtJeans0:{
            masterItem:"tshirtJeans",
            variant:"tshirt_jeans_00",
            price:20,
            daring:0,
            disabled:false,
            isMale:true,
            isFemale:false,
            tags:{
                plain:true,
                white:true,
                blue:true,

            }
        },
        tshirtJeans1:{
            masterItem:"tshirtJeans",
            variant:"tshirt_jeans_01",
            price:20,
            daring:0,
            disabled:false,
            isMale:true,
            isFemale:false,
            tags:{
                plain:true,
                green:true,
                blue:true,
                
            }
        },
        tshirtJeans2:{
            masterItem:"tshirtJeans",
            variant:"tshirt_jeans_02",
            price:20,
            daring:0,
            disabled:false,
            isMale:true,
            isFemale:false,
            tags:{
                plain:true,
                grey:true,
                
            }
        },
        tshirtJeans3:{
            masterItem:"tshirtJeans",
            variant:"tshirt_jeans_03",
            price:20,
            daring:0,
            disabled:false,
            isMale:true,
            isFemale:false,
            tags:{
                plain:true,
                white:true,
                black:true,
                
            }
        },
        tshirtJeans0:{
            masterItem:"tshirtJeans",
            variant:"tshirt_jeans_00",
            price:20,
            daring:0,
            disabled:false,
            isMale:true,
            isFemale:false,
            tags:{
                plain:true,
                white:true,
                blue:true,
                
            }
        },

        //Skirt and Top
        skirtTop0:{
            masterItem:"skirtTop",
            variant:"skirt_top_00",
            price:60,
            daring:5,
            disabled:false,
            isMale:false,
            isFemale:true,
            tags:{
                plain:true,
                pink:true,
                blue:true,
                
            }
        },
        skirtTop1:{
            masterItem:"skirtTop",
            variant:"skirt_top_01",
            price:60,
            daring:5,
            disabled:false,
            isMale:false,
            isFemale:true,
            tags:{
                plain:true,
                red:true,
                blue:true,
                shortskirt:true,
            }
        },
        skirtTop2:{
            masterItem:"skirtTop",
            variant:"skirt_top_02",
            price:60,
            daring:5,
            disabled:false,
            isMale:false,
            isFemale:true,
            tags:{
                plain:true,
                pink:true,
                purple:true,
                shortskirt:true,
            }
        },
        skirtTop3:{
            masterItem:"skirtTop",
            variant:"skirt_top_03",
            price:60,
            daring:5,
            disabled:false,
            isMale:false,
            isFemale:true,
            tags:{
                plain:false,
                black:true,
                sexy:true,
            }
        },
        skirtTop4:{
            masterItem:"skirtTop",
            variant:"skirt_top_04",
            price:60,
            daring:5,
            disabled:false,
            isMale:false,
            isFemale:true,
            tags:{
                plain:true,
                red:true,
                black:true,
                polkadot:true,
            }
        },
        skirtTop5:{
            masterItem:"skirtTop",
            variant:"skirt_top_05",
            price:60,
            daring:5,
            disabled:false,
            isMale:false,
            isFemale:true,
            tags:{
                plain:true,
                pink:true,
                black:true,
            }
        },
        skirtTop6:{
            masterItem:"skirtTop",
            variant:"skirt_top_06",
            price:60,
            daring:5,
            disabled:false,
            isMale:false,
            isFemale:true,
            tags:{
                plain:true,
                pink:true,
                blue:true,
            }
        },
        skirtTop7:{
            masterItem:"skirtTop",
            variant:"skirt_top_07",
            price:60,
            daring:5,
            disabled:false,
            isMale:false,
            isFemale:true,
            tags:{
                plain:true,
                black:true,
            }
        },
        skirtTop8:{
            masterItem:"skirtTop",
            variant:"skirt_top_08",
            price:60,
            daring:5,
            disabled:false,
            isMale:false,
            isFemale:true,
            tags:{
                plain:true,
                white:true,
                cream:true,
                polkadot:true,
            }
        },
        skirtTop9:{
            masterItem:"skirtTop",
            variant:"skirt_top_09",
            price:60,
            daring:5,
            disabled:false,
            isMale:false,
            isFemale:true,
            tags:{
                plain:true,
                pnk:true,
                black:true,
            }
        },
        skirtTop10:{
            masterItem:"skirtTop",
            variant:"skirt_top_10",
            price:60,
            daring:5,
            disabled:false,
            isMale:false,
            isFemale:true,
            tags:{
                plain:true,
                purple:true,
                blue:true,
            }
        },
        skirtTop11:{
            masterItem:"skirtTop",
            variant:"skirt_top_11",
            price:60,
            daring:5,
            disabled:false,
            isMale:false,
            isFemale:true,
            tags:{
                plain:true,
                brown:true,
                black:true,
            }
        },
        skirtTop12:{
            masterItem:"skirtTop",
            variant:"skirt_top_12",
            price:60,
            daring:5,
            disabled:false,
            isMale:false,
            isFemale:true,
            tags:{
                red:true,
                black:true,
                polkadot:true,
                sexy:true,
            }
        },
        skirtTop13:{
            masterItem:"skirtTop",
            variant:"skirt_top_13",
            price:60,
            daring:5,
            disabled:false,
            isMale:false,
            isFemale:true,
            tags:{
                plain:true,
                black:true,
            }
        },
        skirtTop14:{
            masterItem:"skirtTop",
            variant:"skirt_top_14",
            price:60,
            daring:5,
            disabled:false,
            isMale:false,
            isFemale:true,
            tags:{
                plain:true,
                pink:true,
                blue:true,
            }
        },
        skirtTop15:{
            masterItem:"skirtTop",
            variant:"skirt_top_15",
            price:60,
            daring:5,
            disabled:false,
            isMale:false,
            isFemale:true,
            tags:{
                plain:true,
                purple:true,
                blue:true,
            }
        },
        skirtTop16:{
            masterItem:"skirtTop",
            variant:"skirt_top_16",
            price:60,
            daring:5,
            disabled:false,
            isMale:false,
            isFemale:true,
            tags:{
                plain:true,
                blue:true,
                white:true,
                shortskirt:true,
            }
        },
        skirtTop17:{
            masterItem:"skirtTop",
            variant:"skirt_top_17",
            price:60,
            daring:5,
            disabled:false,
            isMale:false,
            isFemale:true,
            tags:{
                sexy:true,
                pink:true,
                black:true,
                shortskirt:true,
            }
        },

        //Casual Dress
        casualDress0:{
            masterItem:"casualDress",
            variant:"dress_casual_00",
            price:50,
            daring:5,
            disabled:false,
            isMale:false,
            isFemale:true,
            tags:{
                plain:true,
                yellow:true,
            }
        },
        casualDress1:{
            masterItem:"casualDress",
            variant:"dress_casual_01",
            price:50,
            daring:5,
            disabled:false,
            isMale:false,
            isFemale:true,
            tags:{
                plain:true,
                pink:true,
            }
        },
        casualDress2:{
            masterItem:"casualDress",
            variant:"dress_casual_02",
            price:50,
            daring:5,
            disabled:false,
            isMale:false,
            isFemale:true,
            tags:{
                plain:true,
                white:true,
            }
        },
        casualDress3:{
            masterItem:"casualDress",
            variant:"dress_casual_03",
            price:50,
            daring:5,
            disabled:false,
            isMale:false,
            isFemale:true,
            tags:{
                plain:true,
                white:true,
                black:true,
                shortskirt:true,
            }
        },
        casualDress4:{
            masterItem:"casualDress",
            variant:"dress_casual_04",
            price:50,
            daring:5,
            disabled:false,
            isMale:false,
            isFemale:true,
            tags:{
                plain:true,
                yellow:true,
            }
        },
        casualDress5:{
            masterItem:"casualDress",
            variant:"dress_casual_05",
            price:50,
            daring:5,
            disabled:false,
            isMale:false,
            isFemale:true,
            tags:{
                plain:true,
                white:true,
            }
        },
        casualDress6:{
            masterItem:"casualDress",
            variant:"dress_casual_06",
            price:50,
            daring:5,
            disabled:false,
            isMale:false,
            isFemale:true,
            tags:{
                plain:true,
                blue:true,
            }
        },
        casualDress7:{
            masterItem:"casualDress",
            variant:"dress_casual_07",
            price:50,
            daring:5,
            disabled:false,
            isMale:false,
            isFemale:true,
            tags:{
                plain:true,
                blue:true,
            }
        },
        casualDress8:{
            masterItem:"casualDress",
            variant:"dress_casual_08",
            price:50,
            daring:5,
            disabled:false,
            isMale:false,
            isFemale:true,
            tags:{
                plain:true,
                white:true,
            }
        },
        casualDress9:{
            masterItem:"casualDress",
            variant:"dress_casual_09",
            price:50,
            daring:5,
            disabled:false,
            isMale:false,
            isFemale:true,
            tags:{
                plain:true,
                orange:true,
            }
        },
        casualDress10:{
            masterItem:"casualDress",
            variant:"dress_casual_10",
            price:50,
            daring:5,
            disabled:false,
            isMale:false,
            isFemale:true,
            tags:{
                plain:true,
                blue:true,
            }
        },
        casualDress11:{
            masterItem:"casualDress",
            variant:"dress_casual_11",
            price:50,
            daring:5,
            disabled:false,
            isMale:false,
            isFemale:true,
            tags:{
                plain:true,
                blue:true,
            }
        },
        casualDress12:{
            masterItem:"casualDress",
            variant:"dress_casual_12",
            price:50,
            daring:5,
            disabled:false,
            isMale:false,
            isFemale:true,
            tags:{
                plain:true,
                blue:true,
                polkadot:true,
            }
        },
        casualDress13:{
            masterItem:"casualDress",
            variant:"dress_casual_13",
            price:50,
            daring:5,
            disabled:false,
            isMale:false,
            isFemale:true,
            tags:{
                plain:true,
                green:true,
            }
        },
        casualDress14:{
            masterItem:"casualDress",
            variant:"dress_casual_14",
            price:50,
            daring:5,
            disabled:false,
            isMale:false,
            isFemale:true,
            tags:{
                plain:true,
                black:true,
                white:true,
            }
        },
        casualDress15:{
            masterItem:"casualDress",
            variant:"dress_casual_15",
            price:50,
            daring:5,
            disabled:false,
            isMale:false,
            isFemale:true,
            tags:{
                plain:true,
                grey:true,
            }
        },
        casualDress16:{
            masterItem:"casualDress",
            variant:"dress_casual_16",
            price:50,
            daring:5,
            disabled:false,
            isMale:false,
            isFemale:true,
            tags:{
                plain:true,
                blue:true,
            }
        },
        casualDress17:{
            masterItem:"casualDress",
            variant:"dress_casual_17",
            price:50,
            daring:5,
            disabled:false,
            isMale:false,
            isFemale:true,
            tags:{
                plain:true,
                yellow:true,
            }
        },
        casualDress18:{
            masterItem:"casualDress",
            variant:"dress_casual_18",
            price:50,
            daring:5,
            disabled:false,
            isMale:false,
            isFemale:true,
            tags:{
                plain:true,
                white:true,
            }
        },
        casualDress19:{
            masterItem:"casualDress",
            variant:"dress_casual_19",
            price:50,
            daring:5,
            disabled:false,
            isMale:false,
            isFemale:true,
            tags:{
                plain:true,
                blue:true,
            }
        },
        casualDress20:{
            masterItem:"casualDress",
            variant:"dress_casual_20",
            price:50,
            daring:5,
            disabled:false,
            isMale:false,
            isFemale:true,
            tags:{
                plain:true,
                pink:true,
            }
        },
        casualDress21:{
            masterItem:"casualDress",
            variant:"dress_casual_21",
            price:50,
            daring:5,
            disabled:false,
            isMale:false,
            isFemale:true,
            tags:{
                plain:true,
                grey:true,
            }
        },
        casualDress22:{
            masterItem:"casualDress",
            variant:"dress_casual_22",
            price:50,
            daring:5,
            disabled:false,
            isMale:false,
            isFemale:true,
            tags:{
                plain:true,
                pink:true,
            }
        },
        casualDress23:{
            masterItem:"casualDress",
            variant:"dress_casual_23",
            price:50,
            daring:5,
            disabled:false,
            isMale:false,
            isFemale:true,
            tags:{
                plain:true,
                blue:true,
            }
        },
        casualDress24:{
            masterItem:"casualDress",
            variant:"dress_casual_24",
            price:50,
            daring:5,
            disabled:false,
            isMale:false,
            isFemale:true,
            tags:{
                plain:true,
                pink:true,
            }
        },
        casualDress25:{
            masterItem:"casualDress",
            variant:"dress_casual_25",
            price:50,
            daring:5,
            disabled:false,
            isMale:false,
            isFemale:true,
            tags:{
                plain:true,
                pink:true,
            }
        },
        casualDress26:{
            masterItem:"casualDress",
            variant:"dress_casual_26",
            price:50,
            daring:5,
            disabled:false,
            isMale:false,
            isFemale:true,
            tags:{
                plain:true,
                pink:true,
            }
        },
        casualDress27:{
            masterItem:"casualDress",
            variant:"dress_casual_27",
            price:50,
            daring:5,
            disabled:false,
            isMale:false,
            isFemale:true,
            tags:{
                plain:true,
                white:true,
            }
        },
        casualDress28:{
            masterItem:"casualDress",
            variant:"dress_casual_28",
            price:50,
            daring:5,
            disabled:false,
            isMale:false,
            isFemale:true,
            tags:{
                plain:true,
                yellow:true,
                polkadot:true,
            }
        },
        casualDress29:{
            masterItem:"casualDress",
            variant:"dress_casual_29",
            price:50,
            daring:5,
            disabled:false,
            isMale:false,
            isFemale:true,
            tags:{
                plain:true,
                red:true,
            }
        },
        casualDress30:{
            masterItem:"casualDress",
            variant:"dress_casual_30",
            price:50,
            daring:5,
            disabled:false,
            isMale:false,
            isFemale:true,
            tags:{
                plain:true,
                white:true,
                polkadot:true,
            }
        },
        casualDress31:{
            masterItem:"casualDress",
            variant:"dress_casual_31",
            price:50,
            daring:5,
            disabled:false,
            isMale:false,
            isFemale:true,
            tags:{
                plain:true,
                blue:true,
            }
        },
        casualDress32:{
            masterItem:"casualDress",
            variant:"dress_casual_32",
            price:50,
            daring:5,
            disabled:false,
            isMale:false,
            isFemale:true,
            tags:{
                plain:true,
                blue:true,
            }
        },
        casualDress33:{
            masterItem:"casualDress",
            variant:"dress_casual_33",
            price:50,
            daring:5,
            disabled:false,
            isMale:false,
            isFemale:true,
            tags:{
                plain:true,
                white:true,
            }
        },
        casualDress34:{
            masterItem:"casualDress",
            variant:"dress_casual_34",
            price:50,
            daring:5,
            disabled:false,
            isMale:false,
            isFemale:true,
            tags:{
                plain:true,
                pink:true,
                polkadot:true,
            }
        },
        casualDress35:{
            masterItem:"casualDress",
            variant:"dress_casual_35",
            price:50,
            daring:5,
            disabled:false,
            isMale:false,
            isFemale:true,
            tags:{
                plain:true,
                pink:true,
            }
        },

        //Slutty Dress
        sluttyDress0:{
            masterItem:"sluttyDress",
            variant:"dress_slutty_00",
            price:160,
            daring:7,
            disabled:false,
            isMale:false,
            isFemale:true,
            tags:{
                slutty:true,
                sexy:true,
                black:true,
            }
        },
        sluttyDress1:{
            masterItem:"sluttyDress",
            variant:"dress_slutty_01",
            price:160,
            daring:7,
            disabled:false,
            isMale:false,
            isFemale:true,
            tags:{
                slutty:true,
                sexy:true,
                pink:true,
                shortskirt:true,
            }
        },
        sluttyDress2:{
            masterItem:"sluttyDress",
            variant:"dress_slutty_02",
            price:160,
            daring:7,
            disabled:false,
            isMale:false,
            isFemale:true,
            tags:{
                slutty:true,
                sexy:true,
                black:true,
                shortskirt:true,
            }
        },
        sluttyDress3:{
            masterItem:"sluttyDress",
            variant:"dress_slutty_03",
            price:160,
            daring:7,
            disabled:false,
            isMale:false,
            isFemale:true,
            tags:{
                slutty:true,
                sexy:true,
                pink:true,
            }
        },
        sluttyDress4:{
            masterItem:"sluttyDress",
            variant:"dress_slutty_04",
            price:160,
            daring:7,
            disabled:false,
            isMale:false,
            isFemale:true,
            tags:{
                slutty:true,
                sexy:true,
                black:true,
            }
        },
        sluttyDress5:{
            masterItem:"sluttyDress",
            variant:"dress_slutty_05",
            price:160,
            daring:7,
            disabled:false,
            isMale:false,
            isFemale:true,
            tags:{
                slutty:true,
                sexy:true,
                pink:true,
            }
        },
        sluttyDress6:{
            masterItem:"sluttyDress",
            variant:"dress_slutty_06",
            price:160,
            daring:7,
            disabled:false,
            isMale:false,
            isFemale:true,
            tags:{
                slutty:true,
                sexy:true,
                black:true,
            }
        },
        sluttyDress7:{
            masterItem:"sluttyDress",
            variant:"dress_slutty_07",
            price:160,
            daring:7,
            disabled:false,
            isMale:false,
            isFemale:true,
            tags:{
                slutty:true,
                sexy:true,
                black:true,
            }
        },
        sluttyDress8:{
            masterItem:"sluttyDress",
            variant:"dress_slutty_08",
            price:160,
            daring:7,
            disabled:false,
            isMale:false,
            isFemale:true,
            tags:{
                slutty:true,
                sexy:true,
                pink:true,
            }
        },
        sluttyDress9:{
            masterItem:"sluttyDress",
            variant:"dress_slutty_09",
            price:160,
            daring:7,
            disabled:false,
            isMale:false,
            isFemale:true,
            tags:{
                slutty:true,
                sexy:true,
                black:true,
            }
        },
        sluttyDress10:{
            masterItem:"sluttyDress",
            variant:"dress_slutty_10",
            price:160,
            daring:7,
            disabled:false,
            isMale:false,
            isFemale:true,
            tags:{
                slutty:true,
                sexy:true,
                black:true,
            }
        },
        sluttyDress11:{
            masterItem:"sluttyDress",
            variant:"dress_slutty_11",
            price:160,
            daring:7,
            disabled:false,
            isMale:false,
            isFemale:true,
            tags:{
                slutty:true,
                sexy:true,
                black:true,
            }
        },
        sluttyDress12:{
            masterItem:"sluttyDress",
            variant:"dress_slutty_12",
            price:160,
            daring:7,
            disabled:false,
            isMale:false,
            isFemale:true,
            tags:{
                slutty:true,
                sexy:true,
                black:true,
                shortskirt:true,
            }
        },
        sluttyDress13:{
            masterItem:"sluttyDress",
            variant:"dress_slutty_13",
            price:160,
            daring:7,
            disabled:false,
            isMale:false,
            isFemale:true,
            tags:{
                slutty:true,
                sexy:true,
                black:true,
            }
        },
        sluttyDress14:{
            masterItem:"sluttyDress",
            variant:"dress_slutty_14",
            price:160,
            daring:7,
            disabled:false,
            isMale:false,
            isFemale:true,
            tags:{
                slutty:true,
                sexy:true,
                black:true,
            }
        },
        sluttyDress15:{
            masterItem:"sluttyDress",
            variant:"dress_slutty_15",
            price:160,
            daring:7,
            disabled:false,
            isMale:false,
            isFemale:true,
            tags:{
                slutty:true,
                sexy:true,
                black:true,
                shortskirt:true,
            }
        },
        sluttyDress16:{
            masterItem:"sluttyDress",
            variant:"dress_slutty_16",
            price:160,
            daring:7,
            disabled:false,
            isMale:false,
            isFemale:true,
            tags:{
                slutty:true,
                sexy:true,
                black:true,
            }
        },
        sluttyDress17:{
            masterItem:"sluttyDress",
            variant:"dress_slutty_17",
            price:160,
            daring:7,
            disabled:false,
            isMale:false,
            isFemale:true,
            tags:{
                slutty:true,
                sexy:true,
                black:true,
            }
        },
        sluttyDress18:{
            masterItem:"sluttyDress",
            variant:"dress_slutty_18",
            price:160,
            daring:7,
            disabled:false,
            isMale:false,
            isFemale:true,
            tags:{
                slutty:true,
                sexy:true,
                black:true,
            }
        },
        sluttyDress19:{
            masterItem:"sluttyDress",
            variant:"dress_slutty_19",
            price:160,
            daring:7,
            disabled:false,
            isMale:false,
            isFemale:true,
            tags:{
                slutty:true,
                sexy:true,
                black:true,
            }
        },
        sluttyDress20:{
            masterItem:"sluttyDress",
            variant:"dress_slutty_20",
            price:160,
            daring:7,
            disabled:false,
            isMale:false,
            isFemale:true,
            tags:{
                slutty:true,
                sexy:true,
                pink:true,
            }
        },
        sluttyDress21:{
            masterItem:"sluttyDress",
            variant:"dress_slutty_21",
            price:160,
            daring:7,
            disabled:false,
            isMale:false,
            isFemale:true,
            tags:{
                slutty:true,
                sexy:true,
                pink:true,
                shortskirt:true,
            }
        },
        sluttyDress22:{
            masterItem:"sluttyDress",
            variant:"dress_slutty_22",
            price:160,
            daring:7,
            disabled:false,
            isMale:false,
            isFemale:true,
            tags:{
                slutty:true,
                sexy:true,
                pink:true,
            }
        },
        sluttyDress23:{
            masterItem:"sluttyDress",
            variant:"dress_slutty_23",
            price:160,
            daring:7,
            disabled:false,
            isMale:false,
            isFemale:true,
            tags:{
                slutty:true,
                sexy:true,
                pink:true,
            }
        },
        sluttyDress24:{
            masterItem:"sluttyDress",
            variant:"dress_slutty_24",
            price:160,
            daring:7,
            disabled:false,
            isMale:false,
            isFemale:true,
            tags:{
                slutty:true,
                sexy:true,
                black:true,
            }
        },
        sluttyDress25:{
            masterItem:"sluttyDress",
            variant:"dress_slutty_25",
            price:160,
            daring:7,
            disabled:false,
            isMale:false,
            isFemale:true,
            tags:{
                slutty:true,
                sexy:true,
                red:true,
                polkadot:true,
            }
        },
        sluttyDress26:{
            masterItem:"sluttyDress",
            variant:"dress_slutty_15",
            price:160,
            daring:7,
            disabled:false,
            isMale:false,
            isFemale:true,
            tags:{
                slutty:true,
                sexy:true,
                pink:true,
            }
        },
        sluttyDress27:{
            masterItem:"sluttyDress",
            variant:"dress_slutty_27",
            price:160,
            daring:7,
            disabled:false,
            isMale:false,
            isFemale:true,
            tags:{
                slutty:true,
                sexy:true,
                black:true,
                pink:true,
            }
        },
        sluttyDress28:{
            masterItem:"sluttyDress",
            variant:"dress_slutty_28",
            price:160,
            daring:7,
            disabled:false,
            isMale:false,
            isFemale:true,
            tags:{
                slutty:true,
                sexy:true,
                red:true,
            }
        },
        sluttyDress29:{
            masterItem:"sluttyDress",
            variant:"dress_slutty_29",
            price:160,
            daring:7,
            disabled:false,
            isMale:false,
            isFemale:true,
            tags:{
                slutty:true,
                sexy:true,
                pink:true,
            }
        },
        sluttyDress30:{
            masterItem:"sluttyDress",
            variant:"dress_slutty_30",
            price:160,
            daring:7,
            disabled:false,
            isMale:false,
            isFemale:true,
            tags:{
                slutty:true,
                sexy:true,
                black:true,
            }
        },
        sluttyDress31:{
            masterItem:"sluttyDress",
            variant:"dress_slutty_31",
            price:160,
            daring:7,
            disabled:false,
            isMale:false,
            isFemale:true,
            tags:{
                slutty:true,
                sexy:true,
                black:true,
            }
        },

        
    }
}
