window.itemTypes={
	NotClothing:   0,
	Underwear:     1,
	Outerwear:     2,
	Shoes:         4,
	Bras:          8,
	Chastity:     16,
	AnalPlug:     32,
	Stockings:    64,
	Earrings:    128,
	Collar:      256,
	Extra:      512,
	Hairband:   1024
},

window.storeType={
	furniture:		0,
	electronics:	1,
	adult:			2,
	male:			3,
	female:			4,
	lingerie:		5,
	footwear:		6,
	jewelry:		7
},

window.quickSlotSets={
	School: 0,
	Casual: 3,
	Slutty: 6,
	Sleep: 9
},

window.itemF={
	itemTwee: function(id) {
		if (State.active.variables.items[id] == null) {
			return false;
		}
		
		return State.active.variables.items[id];
	},
	name: function(item) {
		if (item == null) {
			return false;
		}
		if ((State.active.variables.items[item.id] != null) && (State.active.variables.items[item.id].name != null)) {
			return State.active.variables.items[item.id].name;
		}
		return item.name;
	},
	nameById: function(id) {
		if (window.itemsC[id] != null) {
			if ((State.active.variables.items[id] != null) && (State.active.variables.items[id].name != null)) {
				return State.active.variables.items[id].name;
			}
			return window.itemsC[id].name;
		}
		
		return false;
	},
	deleteItem: function(id) {
		delete State.active.variables.items[id];
	},
	image: function(item) {
		if (item == null) {
			return false;
		}
		if ((State.active.variables.items[item.id] != null) && (State.active.variables.items[item.id].image != null)) {
			return State.active.variables.items[item.id].image;
		}
		return item.image;
	},
	cost: function(item) {
		if (item == null) {
			return false;
		}
		if ((State.active.variables.items[item.id] != null) && (State.active.variables.items[item.id].cost != null)) {
			return State.active.variables.items[item.id].cost;
		}
		return item.cost;
	},
	disabled: function(item) {
		if (item == null) {
			return false;
		}
		if ((State.active.variables.items[item.id] != null) && (State.active.variables.items[item.id].disabled != null)) {
			return State.active.variables.items[item.id].disabled;
		}
		return item.disabled;
	},
	femRec: function(item) {
		if (item == null) {
			return false;
		}
		if (item.femRec == null) {
			return 0;
		}
		if ((State.active.variables.items[item.id] != null) && (State.active.variables.items[item.id].femRec != null)) {
			return State.active.variables.items[item.id].femRec;
		}
		return item.femRec;
	},
	altImage: function(item) {
		if (item == null) {
			return false;
		}
		if ((item.maxAlt != null) && (State.active.variables.items[item.id] != null) && (State.active.variables.items[item.id].curAlt != null)) {
			var itemImage = "";
			itemImage += item.image;
			if (State.active.variables.items[item.id].curAlt <= 9) { itemImage += "0"; }
			itemImage += State.active.variables.items[item.id].curAlt;
			itemImage += ".jpg";
			return itemImage;
		}
		return item.image;
	},
	ownedNumber: function(item) {
		if (item == null) {
			return false;
		}
		var itemCount = 0;
		if ((item.maxAlt != null) && (State.active.variables.items[item.id] != null) && (State.active.variables.items[item.id].ownAlt != null)) {
			var itemAlts = State.active.variables.items[item.id].ownAlt;
			for (var i=0; i < itemAlts.length; i++) {
				if (itemAlts[i]) { itemCount++; }
			}
		}
		if (itemCount == 0 && window.playerCode.owns(item)) {
			itemCount = 1;
		}
		return itemCount;
	},
	maleClothesPurged: function() {
		if (State.active.variables.player.perversion.guardian >= 5) {
			return "I'm not allowed to own male clothes anymore";
		}
		return false;
	},
	crossdressingTask: function() {
		var tasks=State.active.variables.tasksTeacher;
		return (tasks.selfieFemaleClothes.status == 1 || tasks.posingSeductively.status == 1 || tasks.danceAtHome.status == 1 || tasks.crossdressAroundBlock.status == 1 || tasks.crossdressAtPark.status == 1 || tasks.crossdressOnline.status == 1 || tasks.windowshopping.status == 1 || tasks.suckPopsickle.status == 1 || tasks.selfieMallToilets.status == 1 || tasks.girlyDesert.status == 1 || tasks.selfiePublicChastity.status == 1 || tasks.trickGuy.status == 1 || tasks.getHitOn.status == 1 || tasks.TheClubIntro.status == 1);
	},
},

window.itemsC={
	pyjamasMale : {
		id : "pyjamasMale",
		name: "Comfy pajamas",
		clothingType: window.itemTypes.Outerwear,
		cantWearWith: window.itemTypes.Underwear + window.itemTypes.Shoes + window.itemTypes.Stockings + window.itemTypes.Bras,
		ward: false,
		female: false,
		sleepWear: true,
		slutty: false,
		surgery: false,
		school: false,
		store: window.storeType.male,
		cost: 20,
		maxAlt: 1,
		allow: function() { return false; },
		restrict: function() { return window.itemF.maleClothesPurged(); },
		image: "male_pyjamas_"
	},
	silkyTeddy: {	// fem 40
		id: "silkyTeddy",
		name: "Nightie",
		store: window.storeType.lingerie,
		clothingType: window.itemTypes.Outerwear,
		cantWearWith: window.itemTypes.Underwear + window.itemTypes.Shoes + window.itemTypes.Bras,
		ward: false,
		female: true,
		slutty: false,
		school: false,
		sleepWear: true,
		surgery: false,
		femRec: 40,
		cost: 65,
		maxAlt: 5,
		allow: function() { return (State.active.variables.tasksTeacher.selfieNightwear.status == 1); },
		restrict: function() { return false; },
		image: "nightie_"
	},
	casualMale : {
		id: "casualMale",
		name: "T-shirt and jeans",
		clothingType: window.itemTypes.Outerwear,
		cantWearWith: 0,
		ward: false,
		female: false,
		sleepWear: false,
		slutty: false,
		school: false,
		surgery: false,
		store: window.storeType.male,
		cost: 20,
		maxAlt: 3,
		allow: function() { return false; },
		restrict: function() { return window.itemF.maleClothesPurged(); },
		image: "tshirt_jeans_"
	},
	schoolMale : {
		id: "schoolMale",
		name: "School shirt, tie and pants",
		clothingType: window.itemTypes.Outerwear,
		cantWearWith: 0,
		ward: false,
		info: true,
		female: false,
		sleepWear: false,
		slutty: false,
		school: true,
		surgery: false,
		store: window.storeType.male,
		cost: 30,
		allow: function() { return false; },
		restrict: function() { return window.itemF.maleClothesPurged(); },
		image: "school_male.jpg"
	},
	schoolFemale : {	// fem 40
		id: "schoolFemale",
		name: "School dress",
		clothingType: window.itemTypes.Outerwear,
		cantWearWith: 0,
		ward: false,
		info: true,
		female: true,
		sleepWear: false,
		slutty: false,
		surgery: false,
		femRec: 40,
		school: true,
		skirt: true,
		store: window.storeType.female,
		cost: 90,
		maxAlt: 1,
		allow: function() { return ((State.active.variables.events.taskedToWearDressToSchool) || (State.active.variables.player.perversion.teacher >= 4) || (State.active.variables.tasksTeacher.selfieFemaleUniform.status == 1)); },
		restrict: function() { return false; },
		image: "school_female_"
	},
	sluttyschoolFemale : {
		id: "sluttyschoolFemale",
		name: "Slutty school dress",
		clothingType: window.itemTypes.Outerwear,
		cantWearWith: 0,
		ward: false,
		info: true,
		female: true,
		sleepWear: false,
		slutty: true,
		surgery: false,
		femRec: 80,
		school: true,
		skirt: true,
		store: window.storeType.female,
		disabled: true,
		cost: 0,
		allow: function() { return false; },
		restrict: function() { return false; },
		image: "slutty_school_female.jpg"
	},
	skirtTop : {	// fem 40
		id: "skirtTop",
		name: "Skirt and top",
		clothingType: window.itemTypes.Outerwear,
		cantWearWith: 0,
		ward: false,
		female: true,
		sleepWear: false,
		slutty: false,
		school: false,
		store: window.storeType.female,
		skirt: true,
		surgery: false,
		femRec: 40,
		cost: 60,
		maxAlt: 17,
		allow: function() { return window.itemF.crossdressingTask(); },
		restrict: function() { return false; },
		image: "skirt_top_"
	},
	summerDress: {	// fem 40
		id: "summerDress",
		name: "Light summer dress",
		clothingType: window.itemTypes.Outerwear,
		cantWearWith: 0,
		ward: false,
		female: true,
		sleepWear: false,
		slutty: false,
		school: false,
		store: window.storeType.female,
		surgery: false,
		femRec: 40,
		cost: 50,
		maxAlt: 35,
		allow: function() { return window.itemF.crossdressingTask(); },
		restrict: function() { return false; },
		image: "dress_casual_"
	},
	sluttyDress : {	// fem 70
		id: "sluttyDress",
		name: "Slutty dress",
		clothingType: window.itemTypes.Outerwear,
		cantWearWith: 0,
		ward: false,
		female: true,
		sleepWear: false,
		slutty: true,
		school: false,
		store: window.storeType.female,
		surgery: false,
		femRec: 70,
		cost: 160,
		alts: 3,
		maxAlt: 31,
		allow: function() { return false; },
		restrict: function() { return false; },
		image: "dress_slutty_"
	},
	maidOutfit : {
		id: "maidOutfit",
		name: "Maid outfit",
		clothingType: window.itemTypes.Outerwear,
		cantWearWith: 0,
		ward: false,
		female: true,
		sleepWear: false,
		slutty: true,
		school: false,
		store: -1,
		surgery: false,
		disabled: true,
		cost: 0,
		maxAlt: 1,
		allow: function() { return false; },
		restrict: function() { return false; },
		image: "maid_outfit_"
	},
	jocksLucky : {
		id: "jocksLucky",
		name: "Boxers",
		clothingType: window.itemTypes.Underwear,
		cantWearWith: 0,
		female: false,
		sleepWear: false,
		slutty: false,
		school: true,
		surgery: false,
		femRec: 0,
		store: window.storeType.male,
		cost: 10,
		maxAlt: 7,
		allow: function() { return false; },
		restrict: function() { return window.itemF.maleClothesPurged(); },
		image: "lucky_jocks_"
	},
	bra: {	// fem 20
		id: "bra",
		name: "Bra",
		store: window.storeType.lingerie,
		clothingType: window.itemTypes.Bras,
		cantWearWith: 0,
		female: true,
		sleepWear: false,
		slutty: false,
		school: true,
		surgery: false,
		femRec: 20,
		cost: 10,
		maxAlt: 22,
		allow: function() { return window.itemF.crossdressingTask(); },
		restrict: function() { return false; },
		image: "bra_"
	},
	braSexy: {	// fem 30
		id: "braSexy",
		name: "Lacy bra",
		store: window.storeType.lingerie,
		clothingType: window.itemTypes.Bras,
		cantWearWith: 0,
		female: true,
		sleepWear: false,
		slutty: true,
		school: true,
		surgery: false,
		femRec: 30,
		cost: 40,
		maxAlt: 27,
		allow: function() { return (State.active.variables.kinkHypno.clothing && State.active.variables.kink.frilly); },
		restrict: function() { return false; },
		image: "bra_sexy_"
	},
	braLatex: {	// fem 60
		id: "braLatex",
		name: "Latex bra",
		store: window.storeType.lingerie,
		clothingType: window.itemTypes.Bras,
		cantWearWith: 0,
		female: true,
		sleepWear: false,
		slutty: true,
		school: true,
		surgery: false,
		femRec: 60,
		cost: 150,
		maxAlt: 2,
		allow: function() { return (State.active.variables.kinkHypno.clothing && State.active.variables.kink.latex); },
		restrict: function() { return false; },
		image: "bra_latex_"
	},
	pantiesCotton: {	// fem 20
		id: "pantiesCotton",
		name: "Panties",
		store: window.storeType.lingerie,
		clothingType: window.itemTypes.Underwear,
		cantWearWith: 0,
		female: true,
		sleepWear: false,
		slutty: false,
		school: true,
		surgery: false,
		femRec: 20,
		cost: 15,
		maxAlt: 7,
		allow: function() { return (State.active.variables.player.perversion.teacher >= 1 && !window.playerCode.owns(itemsC.pantiesCotton)); },
		restrict: function() { return false; },
		image: "panties_cotton_"
	},
	gString: {	// fem 20
		id: "gString",
		name: "Lacy panties",
		store: window.storeType.lingerie,
		clothingType: window.itemTypes.Underwear,
		cantWearWith: 0,
		female: true,
		sleepWear: false,
		slutty: true,
		school: true,
		surgery: false,
		femRec: 20,
		cost: 35,
		maxAlt: 17,
		allow: function() { return (State.active.variables.events.pantiesInspected || (State.active.variables.kinkHypno.clothing && State.active.variables.kink.frilly)); },
		restrict: function() { return false; },
		image: "panties_sexy_"
	},
	pantiesLatex: {	// fem 60
		id: "pantiesLatex",
		name: "Latex panties",
		store: window.storeType.lingerie,
		clothingType: window.itemTypes.Underwear,
		cantWearWith: 0,
		female: true,
		sleepWear: false,
		slutty: true,
		school: true,
		surgery: false,
		femRec: 60,
		cost: 80,
		maxAlt: 2,
		allow: function() { return (State.active.variables.kinkHypno.clothing && State.active.variables.kink.latex); },
		restrict: function() { return false; },
		image: "panties_latex_"
	},
	socks: {	// fem 30
		id: "socks",
		name: "Socks",
		store: window.storeType.lingerie,
		clothingType: window.itemTypes.Stockings,
		cantWearWith: 0,
		female: true,
		sleepWear: false,
		slutty: false,
		school: true,
		surgery: false,
		femRec: 30,
		cost: 20,
		schoolAlt: 2,
		maxAlt: 24,
		allow: function() { return false; },
		restrict: function() { return false; },
		image: "socks_"
	},
	stockings: {	// fem 40
		id: "stockings",
		name: "Stockings",
		store: window.storeType.lingerie,
		clothingType: window.itemTypes.Stockings,
		cantWearWith: 0,
		female: true,
		sleepWear: false,
		slutty: true,
		school: true,
		surgery: false,
		femRec: 40,
		cost: 50,
		schoolAlt: 5,
		maxAlt: 27,
		allow: function() { return (State.active.variables.kinkHypno.clothing && State.active.variables.kink.frilly); },
		restrict: function() { return false; },
		image: "stockings_"
	},
	stockingsLatex: {	// fem 60
		id: "stockingsLatex",
		name: "Latex stockings",
		store: window.storeType.lingerie,
		clothingType: window.itemTypes.Stockings,
		cantWearWith: 0,
		female: true,
		sleepWear: false,
		slutty: true,
		school: true,
		surgery: false,
		femRec: 60,
		cost: 200,
		schoolAlt: -1,
		maxAlt: 3,
		allow: function() { return (State.active.variables.kinkHypno.clothing && State.active.variables.kink.latex); },
		restrict: function() { return false; },
		image: "stockings_latex_"
	},
	hairband: {	// fem 40
		id: "hairband",
		name: "Hairband",
		clothingType: window.itemTypes.Hairband,
		cantWearWith: 0,
		ward: false,
		store: window.storeType.female,
		cost: 20,
		school: true,
		slutty: false,
		surgery: false,
		femRec: 40,
		female: true,
		schoolAlt: 4,
		maxAlt: 9,
		allow: function() { return false; },
		restrict: function() { return false; },
		image: "hairband_"
	},
	hairbow: {	// fem 40
		id: "hairbow",
		name: "Hairbow",
		clothingType: window.itemTypes.Hairband,
		cantWearWith: 0,
		ward: false,
		store: window.storeType.female,
		cost: 10,
		school: true,
		slutty: false,
		surgery: false,
		femRec: 40,
		female: true,
		schoolAlt: 11,
		maxAlt: 14,
		allow: function() { return (State.active.variables.kinkHypno.clothing && State.active.variables.kink.frilly); },
		restrict: function() { return false; },
		image: "hairbow_"
	},
	choker: {	// fem 50
		id: "choker",
		name: "Choker",
		clothingType: window.itemTypes.Collar,
		cantWearWith: 0,
		ward: false,
		store: window.storeType.female,
		cost: 30,
		school: true,
		slutty: false,
		surgery: false,
		femRec: 50,
		female: true,
		maxAlt: 7,
		allow: function() { return false; },
		restrict: function() { return false; },
		image: "choker_"
	},
	collar: {	// fem 60
		id: "collar",
		name: "Collar",
		clothingType: window.itemTypes.Collar,
		cantWearWith: 0,
		ward: false,
		store: window.storeType.adult,
		cost: 50,
		slutty: true,
		surgery: false,
		femRec: 60,
		female: true,
		maxAlt: 6,
		allow: function() { return false; },
		restrict: function() { return false; },
		image: "collar_"
	},
	collarSissy: {	// fem 90
		id: "collarSissy",
		name: "Sissy collar",
		clothingType: window.itemTypes.Collar,
		cantWearWith: 0,
		ward: false,
		store: window.storeType.adult,
		cost: 50,
		slutty: true,
		schoolSlut: true,
		surgery: false,
		femRec: 90,
		female: true,
		maxAlt: 1,
		allow: function() { return false; },
		restrict: function() { return false; },
		image: "collar_sissy_"
	},
	collarBitch: {	// fem 80
		id: "collarBitch",
		name: "Bitch collar",
		clothingType: window.itemTypes.Collar,
		cantWearWith: 0,
		ward: false,
		store: window.storeType.adult,
		cost: 50,
		slutty: true,
		schoolSlut: true,
		surgery: false,
		femRec: 80,
		female: true,
		allow: function() { return false; },
		restrict: function() { return false; },
		image: "collar_bitch.jpg"
	},
	collarSteel: {	// fem 80
		id: "collarSteel",
		name: "Steel collar",
		clothingType: window.itemTypes.Collar,
		cantWearWith: 0,
		ward: false,
		store: window.storeType.adult,
		cost: 50,
		slutty: true,
		schoolSlut: true,
		surgery: false,
		femRec: 80,
		female: true,
		allow: function() { return false; },
		restrict: function() { return false; },
		image: "collar_steel.jpg"
	},
	sunglasses: {
		id: "sunglasses",
		name: "Sunglasses",
		clothingType: window.itemTypes.Extra,
		cantWearWith: 0,
		ward: false,
		store: window.storeType.jewelry,
		cost: 20,
		school: false,
		slutty: false,
		surgery: false,
		female: false,
		maxAlt: 11,
		allow: function() { return false; },
		restrict: function() { return false; },
		image: "sunglasses_"
	},
	glasses: {
		id: "glasses",
		name: "Decorative glasses",
		clothingType: window.itemTypes.Extra,
		cantWearWith: 0,
		ward: false,
		store: window.storeType.jewelry,
		cost: 20,
		school: true,
		slutty: false,
		surgery: false,
		female: false,
		maxAlt: 9,
		allow: function() { return false; },
		restrict: function() { return false; },
		image: "glasses_"
	},
	blindfold: {
		id: "blindfold",
		name: "Blindfold",
		clothingType: window.itemTypes.Extra,
		cantWearWith: 0,
		ward: false,
		store: -1,
		cost: 20,
		slutty: false,
		surgery: false,
		female: false,
		maxAlt: 3,
		allow: function() { return false; },
		restrict: function() { return false; },
		image: "blindfold_"
	},
	gag: {
		id: "gag",
		name: "Gag",
		clothingType: window.itemTypes.Extra,
		cantWearWith: 0,
		ward: false,
		store: -1,
		cost: 20,
		slutty: false,
		surgery: false,
		female: false,
		maxAlt: 10,
		allow: function() { return false; },
		restrict: function() { return false; },
		image: "gag_"
	},
	diamondStuds: {	// fem 50
		id: "diamondStuds",
		name: "Casual earrings",
		clothingType: window.itemTypes.Earrings,
		cantWearWith: 0,
		ward: false,
		store: window.storeType.jewelry,
		cost: 50,
		school: true,
		slutty: false,
		surgery: false,
		femRec: 50,
		female: true,
		maxAlt: 16,
		allow: function() { return false; },
		restrict: function() { return false; },
		image: "earrings_casual_"
	},
	rubyEarrings: {	// fem 60
		id: "rubyEarrings",
		name: "Classy earrings",
		clothingType: window.itemTypes.Earrings,
		cantWearWith: 0,
		ward: false,
		store: window.storeType.jewelry,
		cost: 200,
		school: true,
		slutty: false,
		surgery: false,
		femRec: 60,
		female: true,
		maxAlt: 16,
		allow: function() { return false; },
		restrict: function() { return false; },
		image: "earrings_classy_"
	},
	hoopsEarrings: {	// fem 60
		id: "hoopsEarrings",
		name: "Flashy earrings",
		clothingType: window.itemTypes.Earrings,
		cantWearWith: 0,
		store: window.storeType.jewelry,
		cost: 100,
		school: true,
		slutty: true,
		surgery: false,
		femRec: 60,
		female: true,
		maxAlt: 16,
		allow: function() { return false; },
		restrict: function() { return false; },
		image: "earrings_flashy_"
	},
	plasticEarrings: {	// fem 60
		id: "plasticEarrings",
		name: "Plastic earrings",
		clothingType: window.itemTypes.Earrings,
		cantWearWith: 0,
		store: window.storeType.jewelry,
		cost: 20,
		slutty: true,
		surgery: false,
		femRec: 60,
		female: true,
		maxAlt: 16,
		allow: function() { return false; },
		restrict: function() { return false; },
		image: "earrings_plastic_"
	},
	sneakers: {
		id: "sneakers",
		name: "Sneakers",
		clothingType: window.itemTypes.Shoes,
		cantWearWith: 0,
		sleepWear: false,
		female: false,
		slutty: false,
		school: false,
		surgery: false,
		femRec: 0,
		store: window.storeType.male,
		cost: 40,
		maxAlt: 3,
		allow: function() { return false; },
		restrict: function() { return window.itemF.maleClothesPurged(); },
		image: "sneakers_"
	},
	schoolShoes: {
		id: "schoolShoes",
		name: "School shoes",
		clothingType: window.itemTypes.Shoes,
		cantWearWith: 0,
		sleepWear: false,
		female: false,
		school: true,
		slutty: false,
		surgery: false,
		femRec: 0,
		store: window.storeType.male,
		cost: 40,
		maxAlt: 2,
		allow: function() { return false; },
		restrict: function() { return window.itemF.maleClothesPurged(); },
		image: "black_shoes_"
	},
	flats: {	// fem 40
		id: "flats",
		name: "Flats",
		clothingType: window.itemTypes.Shoes,
		cantWearWith: 0,
		female: true,
		sleepWear: false,
		slutty: false,
		school: true,
		store: window.storeType.footwear,
		surgery: false,
		femRec: 40,
		cost: 40,
		schoolAlt: 9,
		maxAlt: 33,
		allow: function() { return ((State.active.variables.player.perversion.teacher >= 4) || window.itemF.crossdressingTask()); },
		restrict: function() { return false; },
		image: "flats_"
	},
	girlsneakers: {	// fem 40
		id: "girlsneakers",
		name: "Girls' sneakers",
		clothingType: window.itemTypes.Shoes,
		cantWearWith: 0,
		female: true,
		sleepWear: false,
		slutty: false,
		school: false,
		store: window.storeType.footwear,
		surgery: false,
		femRec: 40,
		cost: 60,
		maxAlt: 10,
		allow: function() { return false; },
		restrict: function() { return false; },
		image: "girlsneakers_"
	},
	boots: {	// fem 50
		id: "boots",
		name: "Women's boots",
		clothingType: window.itemTypes.Shoes,
		cantWearWith: 0,
		female: true,
		sleepWear: false,
		slutty: false,
		school: true,
		store: window.storeType.footwear,
		surgery: false,
		femRec: 50,
		cost: 80,
		schoolAlt: 5,
		maxAlt: 21,
		allow: function() { return window.itemF.crossdressingTask(); },
		restrict: function() { return false; },
		image: "boots_"
	},
	heeledBoots: {	// fem 55
		id: "heeledBoots",
		name: "High-heeled boots",
		clothingType: window.itemTypes.Shoes,
		cantWearWith: 0,
		female: true,
		sleepWear: false,
		slutty: false,
		school: false,
		store: window.storeType.footwear,
		surgery: false,
		femRec: 55,
		cost: 120,
		schoolAlt: 12,
		maxAlt: 23,
		allow: function() { return false; },
		restrict: function() { return false; },
		image: "boots_heeled_"
	},
	highBoots: {	// fem 70
		id: "highBoots",
		name: "Thigh-high heeled boots",
		clothingType: window.itemTypes.Shoes,
		cantWearWith: 0,
		female: true,
		sleepWear: false,
		slutty: true,
		school: false,
		store: window.storeType.footwear,
		surgery: false,
		femRec: 70,
		cost: 200,
		maxAlt: 13,
		allow: function() { return false; },
		restrict: function() { return false; },
		image: "boots_high_"
	},
	highHeel3: {	// fem 45
		id: "highHeel3",
		name: "High heels",
		clothingType: window.itemTypes.Shoes,
		cantWearWith: 0,
		female: true,
		sleepWear: false,
		slutty: true,
		school: true,
		store: window.storeType.footwear,
		surgery: false,
		femRec: 45,
		cost: 100,
		schoolAlt: 9,
		maxAlt: 18,
		allow: function() { return ((State.active.variables.player.perversion.teacher >= 7) || window.itemF.crossdressingTask()); },
		restrict: function() { return false; },
		image: "heels_"
	},
	stilettoHeels: {	// fem 70
		id: "stilettoHeels",
		name: "Stripper heels",
		clothingType: window.itemTypes.Shoes,
		cantWearWith: 0,
		female: true,
		sleepWear: false,
		slutty: true,
		school: true,
		schoolSlut: true,
		store: window.storeType.footwear,
		surgery: false,
		femRec: 70,
		cost: 300,
		schoolAlt: -1,
		maxAlt: 17,
		allow: function() { return false; },
		restrict: function() { return false; },
		image: "heels_stripper_"
	},
	balletHeels: {
		id: "balletHeels",
		name: "Ballet heels",
		clothingType: window.itemTypes.Shoes,
		cantWearWith: 0,
		female: true,
		sleepWear: false,
		slutty: true,
		school: false,
		store: -1,
		surgery: false,
		cost: 300,
		maxAlt: 13,
		allow: function() { return false; },
		restrict: function() { return false; },
		image: "heels_ballet_"
	},
	chastityDevice: {	// fem 25
		id: "chastityDevice",
		name: "CB-6000 chastity device",
		clothingType: window.itemTypes.Chastity,
		cantWearWith: 0,
		store: window.storeType.adult,
		cost: 50,
		surgery: false,
		femRec: 25,
		female: true,
		allow: function() { return (State.active.variables.player.perversion.teacher >= 2); },
		restrict: function() { return false; },
		image: "chastity_cb6000.jpg"
	},
	buttPlugHeart: {	// fem 25
		id: "buttPlugHeart",
		name: "Butt-plug with jeweled heart",
		clothingType: window.itemTypes.AnalPlug,
		cantWearWith: 0,
		store: window.storeType.adult,
		cost: 40,
		surgery: false,
		femRec: 25,
		female: true,
		allow: function() { return (State.active.variables.player.perversion.teacher >= 2); },
		restrict: function() {
			if (State.active.variables.flags.buttplugLost) { return "No way, not after that humiliating accident at the class"; }
			return false;
		},
		image: "buttplug_heart.jpg"
	},
	buttPlugDildo: {	// fem 60
		id: "buttPlugDildo",
		name: "Butt-plug dildo",
		clothingType: window.itemTypes.AnalPlug,
		cantWearWith: 0,
		store: window.storeType.adult,
		cost: 80,
		surgery: false,
		femRec: 60,
		female: true,
		allow: function() { return false; },
		restrict: function() { return false; },
		image: "buttplug_dildo.jpg"
	},
	buttPlugVibro: {	// fem 90
		id: "buttPlugVibro",
		name: "Vibro butt-plug",
		clothingType: window.itemTypes.AnalPlug,
		cantWearWith: 0,
		store: -1,
		cost: 200,
		surgery: false,
		femRec: 90,
		female: true,
		allow: function() { return false; },
		restrict: function() { return false; },
		image: "buttplug_vibro.jpg"
	},
	buttPlugInflate: {	// fem 90
		id: "buttPlugInflate",
		name: "Inflatable butt-plug",
		clothingType: window.itemTypes.AnalPlug,
		cantWearWith: 0,
		store: -1,
		cost: 200,
		surgery: false,
		femRec: 90,
		female: true,
		allow: function() { return false; },
		restrict: function() { return false; },
		image: "buttplug_inflate_0.jpg"
	},
	remotePlugs: {
		id: "remotePlugs",
		name: "Remote controlled butt-plug",
		clothingType: window.itemTypes.NotClothing,
		cantWearWith: 0,
		store: window.storeType.adult,
		disabled: true,
		cost: 100,
		surgery: false,
		femRec: 40,
		female: true,
		allow: function() { return false; },
		restrict: function() { return false; },
		image: "buttplug_vibro.jpg"
	},
	alarmClock: {
		id: "alarmClock",
		name: "Alarm clock",
		store: window.storeType.electronics,
		clothingType: window.itemTypes.NotClothing,
		surgery: false,
		allow: function() { return false; },
		restrict: function() {
			if ((State.active.variables.player.perversion.guardian >= 5) || State.active.variables.flags.dreamgameCaught) { return "Not needed anymore"; }
			return false;
		},
		image: "alarm_clock.jpg",
		cost: 15
	},
	batteries: {
		id: "batteries",
		name: "Batteries (Cheap Brand)",
		store: window.storeType.electronics,
		clothingType: window.itemTypes.NotClothing,
		surgery: false,
		checkRestrict: true,
		allow: function() { return false; },
		restrict: function() {
			if ((State.active.variables.player.perversion.guardian >= 3) || State.active.variables.flags.guardianSnoopingCaught) {
				return "Not needed anymore";
			}
			return false;
		},
		image: "battery.jpg",
		cost: 5
	},
	spyCamera: {
		id: "spyCamera",
		name: "Wifi spy camera",
		store: window.storeType.electronics,
		clothingType: window.itemTypes.NotClothing,
		surgery: false,
		allow: function() { return false; },
		restrict: function() { return false; },
		image: "spy_camera.jpg",
		cost: 80
	},
	camera: {
		id: "camera",
		name: "Camera",
		store: window.storeType.electronics,
		clothingType: window.itemTypes.NotClothing,
		surgery: false,
		allow: function() { return false; },
		restrict: function() { return false; },
		image: "camera.jpg",
		cost: 0
	},
	stunGun: {
		id: "stunGun",
		name: "Stun gun",
		store: window.storeType.electronics,
		clothingType: window.itemTypes.NotClothing,
		surgery: false,
		allow: function() { return false; },
		restrict: function() { return false; },
		image: "stun_gun.jpg",
		cost: 200
	},
	roomGamer: {
		id: "roomGamer",
		name: "Video games themed decorations",
		store: window.storeType.furniture,
		clothingType: window.itemTypes.NotClothing,
		surgery: false,
		allow: function() { return false; },
		restrict: function() { return false; },
		image: "room_gamer.jpg",
		cost: 100
	},
	roomPunk: {
		id: "roomPunk",
		name: "Various punky decorations",
		store: window.storeType.furniture,
		clothingType: window.itemTypes.NotClothing,
		surgery: false,
		allow: function() { return false; },
		restrict: function() { return false; },
		image: "room_punk.jpg",
		cost: 80
	},
	roomGeek: {
		id: "roomGeek",
		name: "Fantasy themed decorations",
		store: window.storeType.furniture,
		clothingType: window.itemTypes.NotClothing,
		surgery: false,
		allow: function() { return false; },
		restrict: function() { return false; },
		image: "room_geek.jpg",
		cost: 120
	},
	roomSport: {
		id: "roomSport",
		name: "Sport themed decorations",
		store: window.storeType.furniture,
		clothingType: window.itemTypes.NotClothing,
		surgery: false,
		allow: function() { return false; },
		restrict: function() { return false; },
		image: "room_sport.jpg",
		cost: 90
	},
	roomGirly: {
		id: "roomGirly",
		name: "Girly girl room decorations",
		store: window.storeType.furniture,
		clothingType: window.itemTypes.NotClothing,
		surgery: false,
		allow: function() { return false; },
		restrict: function() { return false; },
		image: "room_girly_girl.jpg",
		cost: 0
	},
	lampClassic: {
		id: "lampClassic",
		name: "Classic lamp",
		store: window.storeType.furniture,
		clothingType: window.itemTypes.NotClothing,
		surgery: false,
		allow: function() { return false; },
		restrict: function() { return false; },
		image: "lamp_classic.jpg",
		cost: 20
	},
	lampPurple: {
		id: "lampPurple",
		name: "Purple lamp",
		store: window.storeType.furniture,
		clothingType: window.itemTypes.NotClothing,
		surgery: false,
		allow: function() { return false; },
		restrict: function() { return false; },
		image: "lamp_purple.jpg",
		cost: 35
	},
	lampTube: {
		id: "lampTube",
		name: "Multicolor lamp",
		store: window.storeType.furniture,
		clothingType: window.itemTypes.NotClothing,
		surgery: false,
		allow: function() { return false; },
		restrict: function() { return false; },
		image: "lamp_tube.jpg",
		cost: 25
	},
	vibrator: {
		id: "vibrator",
		name: "Vibrator",
		store: window.storeType.adult,
		clothingType: window.itemTypes.NotClothing,
		cost: 60,
		surgery: false,
		femRec: 40,
		maxAlt: 2,
		allow: function() { return false; },
		restrict: function() { return false; },
		image: "vibrator_"
	},
	massageOil: {
		id: "massageOil",
		name: "Sensuous massage oil",
		store: window.storeType.adult,
		clothingType: window.itemTypes.NotClothing,
		disabled: true,
		cost: 20,
		surgery: false,
		female: true,
		allow: function() { return false; },
		restrict: function() { return false; },
		image: "massage_oil.jpg"
	},
	playgirlMagazine: {
		id: "playgirlMagazine",
		name: "Playgirl magazine",
		store: -1,
		clothingType: window.itemTypes.NotClothing,
		cost: 15,
		surgery: false,
		allow: function() { return false; },
		restrict: function() { return false; },
		image: "playgirl_magazine.jpg",
		female: true
	},
	nailPolish: {
		id: "nailPolish",
		name: "Nail polish",
		store: window.storeType.jewelry,
		clothingType: window.itemTypes.NotClothing,
		disabled: true,
		cost: 10,
		surgery: false,
		female: true,
		allow: function() { return false; },
		restrict: function() { return false; },
		image: "nail_polish.jpg"
	},
	Depilatory: {				// fem 30
		id: "Depilatory",
		name: "Depilatory",
		store: -2,
		clothingType: window.itemTypes.NotClothing,
		surgery: true,
		femRec: 30,
		cost: 30,
		allow: function() { return false; },
		restrict: function() { return false; },
		image: "hr_depilatory.jpg"
	},
	Waxing: {					// fem 30
		id: "Waxing",
		name: "Waxing",
		store: -2,
		clothingType: window.itemTypes.NotClothing,
		surgery: true,
		femRec: 30,
		cost: 20,
		allow: function() { return false; },
		restrict: function() { return false; },
		image: "hr_waxing.jpg"
	},
	LaserHairRemoval: {			// fem 60
		id: "LaserHairRemoval",
		name: "Laser hair removal",
		store: -2,
		clothingType: window.itemTypes.NotClothing,
		surgery: true,
		femRec: 60,
		cost: 200,
		allow: function() { return false; },
		restrict: function() { return false; },
		image: "hr_laser.jpg"
	},
	Manicure: {					// fem 50
		id: "Manicure",
		name: "Manicure",
		store: -2,
		clothingType: window.itemTypes.NotClothing,
		surgery: true,
		femRec: 50,
		cost: 20,
		allow: function() { return false; },
		restrict: function() { return false; },
		image: "manicure.jpg"
	},
	GarishManicure: {			// fem 90
		id: "GarishManicure",
		name: "Garish manicure",
		store: -2,
		clothingType: window.itemTypes.NotClothing,
		surgery: true,
		femRec: 90,
		cost: 200,
		allow: function() { return false; },
		restrict: function() { return false; },
		image: "manicure_garish.jpg"
	},
	PermanentManicure: {		// fem 90
		id: "PermanentManicure",
		name: "Garish manicure",
		store: -2,
		clothingType: window.itemTypes.NotClothing,
		surgery: true,
		femRec: 90,
		cost: 200,
		allow: function() { return false; },
		restrict: function() { return false; },
		image: "catalysator.jpg"
	},
	HairShort: {					// fem 20
		id: "HairShort",
		name: "Short haircut",
		store: -2,
		clothingType: window.itemTypes.NotClothing,
		surgery: true,
		femRec: 30,
		cost: 20,
		allow: function() { return false; },
		restrict: function() { return false; },
		image: "hair_short_brown.jpg"
	},
	HairMedium: {					// fem 30
		id: "HairMedium",
		name: "Medium haircut",
		clothingType: window.itemTypes.NotClothing,
		store: -2,
		surgery: true,
		femRec: 35,
		cost: 30,
		allow: function() { return false; },
		restrict: function() { return false; },
		image: "hair_medium_brown.jpg"
	},
	HairLong: {						// fem 35
		id: "HairLong",
		name: "Long haircut",
		clothingType: window.itemTypes.NotClothing,
		store: -2,
		surgery: true,
		femRec: 40,
		cost: 50,
		allow: function() { return false; },
		restrict: function() { return false; },
		image: "hair_long_brown.jpg"
	},
	HairPigtails: {					// fem 35
		id: "HairPigtails",
		name: "Pigtails",
		clothingType: window.itemTypes.NotClothing,
		store: -2,
		surgery: true,
		femRec: 40,
		cost: 30,
		allow: function() { return false; },
		restrict: function() { return false; },
		image: "hair_pigtails_brown.jpg"
	},
	HairCurly: {					// fem 40
		id: "HairCurly",
		name: "Curly hair",
		clothingType: window.itemTypes.NotClothing,
		store: -2,
		surgery: true,
		femRec: 50,
		cost: 40,
		allow: function() { return false; },
		restrict: function() { return false; },
		image: "hair_curly_brown.jpg"
	},
	SubtleMakeup: {				// fem 30
		id: "SubtleMakeup",
		name: "Subtle makeup",
		clothingType: window.itemTypes.NotClothing,
		store: -2,
		surgery: true,
		femRec: 30,
		cost: 10,
		allow: function() { return false; },
		restrict: function() { return false; },
		image: "makeup_subtle.jpg"
	},
	NormalMakeup: {				// fem 50
		id: "NormalMakeup",
		name: "Professional makeup",
		clothingType: window.itemTypes.NotClothing,
		store: -2,
		surgery: true,
		femRec: 50,
		cost: 30,
		allow: function() { return false; },
		restrict: function() { return false; },
		image: "makeup_normal.jpg"
	},
	BimboMakeup: {				// fem 60
		id: "BimboMakeup",
		name: "Bimbo makeup",
		clothingType: window.itemTypes.NotClothing,
		store: -2,
		surgery: true,
		femRec: 70,
		cost: 50,
		allow: function() { return false; },
		restrict: function() { return false; },
		image: "makeup_bimbo.jpg"
	},
	HeavyMakeup: {				// fem 80
		id: "HeavyMakeup",
		name: "Heavy makeup",
		clothingType: window.itemTypes.NotClothing,
		store: -2,
		surgery: true,
		femRec: 80,
		cost: 15,
		allow: function() { return false; },
		restrict: function() { return false; },
		image: "makeup_heavy.jpg"
	},
	PermanentSubtleMakeup: {		// fem 90
		id: "PermanentSubtleMakeup",
		name: "Permanent subtle makeup",
		clothingType: window.itemTypes.NotClothing,
		store: -2,
		surgery: true,
		femRec: 90,
		cost: 100,
		allow: function() { return false; },
		restrict: function() { return false; },
		image: "makeup_subtle.jpg"
	},
	PermanentNormalMakeup: {		// fem 90
		id: "PermanentNormalMakeup",
		name: "Permanent makeup",
		clothingType: window.itemTypes.NotClothing,
		store: -2,
		surgery: true,
		femRec: 90,
		cost: 200,
		allow: function() { return false; },
		restrict: function() { return false; },
		image: "makeup_normal.jpg"
	},
	PermanentBimboMakeup: {			// fem 90
		id: "PermanentBimboMakeup",
		name: "Permanent bimbo makeup",
		clothingType: window.itemTypes.NotClothing,
		store: -2,
		surgery: true,
		femRec: 90,
		cost: 300,
		allow: function() { return false; },
		restrict: function() { return false; },
		image: "makeup_bimbo.jpg"
	},
	PermanentHeavyMakeup: {			// fem 100
		id: "PermanentHeavyMakeup",
		name: "Permanent heavy makeup",
		clothingType: window.itemTypes.NotClothing,
		store: -2,
		surgery: true,
		femRec: 100,
		cost: 200,
		allow: function() { return false; },
		restrict: function() { return false; },
		image: "makeup_heavy.jpg"
	},
	tattooSissy: {			// fem 80
		id: "tattooSissy",
		name: "Sissy tattoo",
		clothingType: window.itemTypes.NotClothing,
		store: -2,
		surgery: false,
		femRec: 80,
		cost: 10,
		allow: function() { return false; },
		restrict: function() { return false; },
		image: "tattoo_sissy.jpg"
	},
	tattooSlut: {			// fem 80
		id: "tattooSlut",
		name: "Slut tattoo",
		clothingType: window.itemTypes.NotClothing,
		store: -2,
		surgery: false,
		femRec: 80,
		cost: 60,
		allow: function() { return false; },
		restrict: function() { return false; },
		image: "tattoo_slut.jpg"
	},
	tattooStupidWhore: {	// fem 80
		id: "tattooStupidWhore",
		name: "Stupid whore tattoo",
		clothingType: window.itemTypes.NotClothing,
		store: -2,
		surgery: false,
		femRec: 80,
		cost: 40,
		allow: function() { return false; },
		restrict: function() { return false; },
		image: "tattoo_stupidwhore.jpg"
	},
	tattooStockings: {		// fem 70
		id: "tattooStockings",
		name: "Stockings tattoo",
		clothingType: window.itemTypes.NotClothing,
		store: -2,
		surgery: false,
		femRec: 70,
		cost: 80,
		allow: function() { return false; },
		restrict: function() { return false; },
		image: "tattoo_stockings.jpg"
	},
	tattooHeart: {			// fem 80
		id: "tattooHeart",
		name: "Heart tattoo",
		clothingType: window.itemTypes.NotClothing,
		store: -2,
		surgery: false,
		femRec: 80,
		cost: 15,
		allow: function() { return false; },
		restrict: function() { return false; },
		image: "tattoo_heart.jpg"
	},
	tattooBunny: {			// fem 70
		id: "tattooBunny",
		name: "Bunny tattoo",
		clothingType: window.itemTypes.NotClothing,
		store: -2,
		surgery: false,
		femRec: 70,
		cost: 20,
		allow: function() { return false; },
		restrict: function() { return false; },
		image: "tattoo_bunny.jpg"
	},
	tattooButterfly: {		// fem 70
		id: "tattooButterfly",
		name: "Butterfly tattoo",
		clothingType: window.itemTypes.NotClothing,
		store: -2,
		surgery: false,
		femRec: 70,
		cost: 100,
		allow: function() { return false; },
		restrict: function() { return false; },
		image: "tattoo_butterfly.jpg"
	},
	beautyMark: {			// fem 70
		id: "beautyMark",
		name: "Beauty mark",
		clothingType: window.itemTypes.NotClothing,
		store: -2,
		surgery: false,
		femRec: 70,
		cost: 10,
		allow: function() { return false; },
		restrict: function() { return false; },
		image: "beauty_mark.jpg"
	},
	LipsEnhancing: {			// fem 55
		id: "LipsEnhancing",
		name: "Lips enhancing",
		clothingType: window.itemTypes.NotClothing,
		store: -2,
		surgery: true,
		femRec: 60,
		cost: 30,
		allow: function() { return false; },
		restrict: function() { return false; },
		image: "bm_lips.gif"
	},
	LipsEnhancingXL: {			// fem 80
		id: "LipsEnhancingXL",
		name: "Lips enhancing extra",
		clothingType: window.itemTypes.NotClothing,
		store: -2,
		surgery: true,
		femRec: 80,
		cost: 100,
		allow: function() { return false; },
		restrict: function() { return false; },
		image: "bm_lips_xl.gif"
	},
	LipsPermanent: {			// fem 90
		id: "LipsPermanent",
		name: "Lips permanent catalysator",
		clothingType: window.itemTypes.NotClothing,
		store: -2,
		surgery: true,
		femRec: 90,
		cost: 500,
		allow: function() { return false; },
		restrict: function() { return false; },
		image: "catalysator.jpg"
	},
	AssEnhancing: {				// fem 60
		id: "AssEnhancing",
		name: "Ass enhancing",
		clothingType: window.itemTypes.NotClothing,
		store: -2,
		surgery: true,
		femRec: 65,
		cost: 30,
		allow: function() { return false; },
		restrict: function() { return false; },
		image: "bm_ass.gif"
	},
	AssEnhancingXL: {			// fem 80
		id: "AssEnhancingXL",
		name: "Ass enhancing extra",
		clothingType: window.itemTypes.NotClothing,
		store: -2,
		surgery: true,
		femRec: 80,
		cost: 100,
		allow: function() { return false; },
		restrict: function() { return false; },
		image: "bm_ass_xl.gif"
	},
	AssPermanent: {				// fem 90
		id: "AssPermanent",
		name: "Ass permanent catalysator",
		clothingType: window.itemTypes.NotClothing,
		store: -2,
		surgery: true,
		femRec: 90,
		cost: 500,
		allow: function() { return false; },
		restrict: function() { return false; },
		image: "catalysator.jpg"
	},
	PenisShrinking: {			// fem 70
		id: "PenisShrinking",
		name: "Penis shrinking",
		clothingType: window.itemTypes.NotClothing,
		store: -2,
		surgery: true,
		femRec: 90,
		cost: 20,
		allow: function() { return false; },
		restrict: function() { return false; },
		image: "small_penis.jpg"
	},
	PiercingEars: {			// fem 50
		id: "PiercingEars",
		name: "Ears piercing",
		clothingType: window.itemTypes.NotClothing,
		store: -2,
		surgery: false,
		femRec: 60,
		cost: 30,
		allow: function() { return false; },
		restrict: function() { return false; },
		image: "piercing_ears.jpg"
	},
	PiercingLips: {			// fem 60
		id: "PiercingLips",
		name: "Lip piercing",
		clothingType: window.itemTypes.NotClothing,
		store: -2,
		surgery: false,
		femRec: 70,
		cost: 20,
		allow: function() { return false; },
		restrict: function() { return false; },
		image: "piercing_lips.jpg"
	},
	PiercingNose: {			// fem 60
		id: "PiercingNose",
		name: "Nose piercing",
		clothingType: window.itemTypes.NotClothing,
		store: -2,
		surgery: false,
		femRec: 70,
		cost: 40,
		allow: function() { return false; },
		restrict: function() { return false; },
		image: "piercing_nose.jpg"
	},
	PiercingBelly: {		// fem 60
		id: "PiercingBelly",
		name: "Belly piercing",
		clothingType: window.itemTypes.NotClothing,
		store: -2,
		surgery: false,
		femRec: 70,
		cost: 50,
		allow: function() { return false; },
		restrict: function() { return false; },
		image: "piercing_belly.jpg"
	},
	PiercingTongue: {		// fem 70
		id: "PiercingTongue",
		name: "Tongue piercing",
		clothingType: window.itemTypes.NotClothing,
		store: -2,
		surgery: false,
		femRec: 70,
		cost: 30,
		allow: function() { return false; },
		restrict: function() { return false; },
		image: "piercing_tongue.jpg"
	},
	PiercingNipples: {		// fem 70
		id: "PiercingNipples",
		name: "Nipples piercing",
		clothingType: window.itemTypes.NotClothing,
		store: -2,
		surgery: false,
		femRec: 70,
		cost: 80,
		allow: function() { return false; },
		restrict: function() { return false; },
		image: "piercing_nipples.jpg"
	},
	breastImplantsA: {			// fem 50
		id: "breastImplantsA",
		name: "Breast implants - small",
		clothingType: window.itemTypes.NotClothing,
		store: -2,
		surgery: true,
		femRec: 50,
		cost: 50,
		allow: function() { return false; },
		restrict: function() { return false; },
		image: "breast_implants_stage1.gif"
	},
	breastImplantsB: {			// fem 60
		id: "breastImplantsB",
		name: "Breast implants - average",
		clothingType: window.itemTypes.NotClothing,
		store: -2,
		surgery: true,
		femRec: 60,
		cost: 100,
		allow: function() { return false; },
		restrict: function() { return false; },
		image: "breast_implants_stage2.gif"
	},
	breastImplantsC: {			// fem 70
		id: "breastImplantsC",
		name: "Breast implants - big",
		clothingType: window.itemTypes.NotClothing,
		store: -2,
		surgery: true,
		femRec: 70,
		cost: 200,
		allow: function() { return false; },
		restrict: function() { return false; },
		image: "breast_implants_stage3.gif"
	},
	breastImplantsDD: {			// fem 80
		id: "breastImplantsDD",
		name: "Breast implants - massive",
		clothingType: window.itemTypes.NotClothing,
		store: -2,
		surgery: true,
		femRec: 80,
		cost: 400,
		allow: function() { return false; },
		restrict: function() { return false; },
		image: "breast_implants_stage4.gif"
	},
	breastPermanent: {			// fem 90
		id: "breastPermanent",
		name: "Breast permanent catalysator",
		clothingType: window.itemTypes.NotClothing,
		store: -2,
		surgery: true,
		femRec: 90,
		cost: 1000,
		allow: function() { return false; },
		restrict: function() { return false; },
		image: "catalysator.jpg"
	},
	analSmoothing1: {		// fem 80
		id: "analSmoothing1",
		name: "Anal smoothing",
		clothingType: window.itemTypes.NotClothing,
		store: -2,
		surgery: true,
		femRec: 80,
		cost: 50,
		allow: function() { return false; },
		restrict: function() { return false; },
		image: "ass_smoothening_1.jpg"
	},
	analSmoothing2: {		// fem 90
		id: "analSmoothing2",
		name: "Anal smoothing plus",
		clothingType: window.itemTypes.NotClothing,
		store: -2,
		surgery: true,
		femRec: 90,
		cost: 100,
		allow: function() { return false; },
		restrict: function() { return false; },
		image: "ass_smoothening_2.jpg"
	},
	analSmoothing3: {		// fem 100
		id: "analSmoothing3",
		name: "Anal smoothing extra",
		clothingType: window.itemTypes.NotClothing,
		store: -2,
		surgery: true,
		femRec: 100,
		cost: 150,
		allow: function() { return false; },
		restrict: function() { return false; },
		image: "ass_smoothening_3.jpg"
	},
	softeningFacial: {			// fem 60
		id: "softeningFacial",
		name: "Facial softening",
		clothingType: window.itemTypes.NotClothing,
		store: -2,
		surgery: true,
		femRec: 60,
		cost: 100,
		allow: function() { return false; },
		restrict: function() { return false; },
		image: "facial_softening.jpg"
	},
	surgeryFacial: {			// fem 80
		id: "surgeryFacial",
		name: "Facial softening extra",
		clothingType: window.itemTypes.NotClothing,
		store: -2,
		surgery: true,
		femRec: 80,
		cost: 300,
		allow: function() { return false; },
		restrict: function() { return false; },
		image: "facial_surgery.jpg"
	},
	freckles: {				// fem 20
		id: "freckles",
		name: "Freckles application",
		clothingType: window.itemTypes.NotClothing,
		store: -2,
		surgery: true,
		femRec: 20,
		cost: 50,
		allow: function() { return false; },
		restrict: function() { return false; },
		image: "freckles.jpg"
	},
	noseClassic: {			// fem 50
		id: "noseClassic",
		name: "Classic nose",
		clothingType: window.itemTypes.NotClothing,
		store: -2,
		surgery: true,
		femRec: 50,
		cost: 100,
		allow: function() { return false; },
		restrict: function() { return false; },
		image: "nose_classic.jpg"
	},
	noseButton: {			// fem 50
		id: "noseButton",
		name: "Button nose",
		clothingType: window.itemTypes.NotClothing,
		store: -2,
		surgery: true,
		femRec: 50,
		cost: 200,
		allow: function() { return false; },
		restrict: function() { return false; },
		image: "nose_button.jpg"
	},
	nosePiggy: {			// fem 50
		id: "nosePiggy",
		name: "Piggy nose",
		clothingType: window.itemTypes.NotClothing,
		store: -2,
		surgery: true,
		femRec: 50,
		cost: 20,
		allow: function() { return false; },
		restrict: function() { return false; },
		image: "nose_piggy.jpg"
	},
	surgerySexualReassignment: {	// fem 100
		id: "surgerySexualReassignment",
		name: "Female sexual reassignment surgery",
		clothingType: window.itemTypes.NotClothing,
		store: -2,
		surgery: true,
		femRec: 100,
		cost: 2000,
		allow: function() { return false; },
		restrict: function() { return false; },
		image: "sexual_reassignment.jpg"
	},
	token : {
		id: "token",
		name: "token",
		clothingType: window.itemTypes.NotClothing,
		female: false,
		sleepWear: false,
		slutty: false,
		surgery: false,
		school: false,
		store: -1,
		cost: 0,
		allow: function() { return false; },
		restrict: function() { return false; },
		image: "sexual_reassignment.jpg"
	}
},

window.itemSubTypes=[
	[
		"Outfits",
		"pyjamasMale",
		"silkyTeddy",
		"casualMale",
		"schoolMale",
		"schoolFemale",
		"sluttyschoolFemale",
		"skirtTop",
		"summerDress",
		"sluttyDress",
		"maidOutfit"
	],
	[
		"Undergarments",
		"jocksLucky",
		"bra",
		"braLatex",
		"braSexy",
		"pantiesCotton",
		"pantiesLatex",
		"gString",
		"socks",
		"stockingsLatex",
		"stockings"
	],
	[
		"Footwear",
		"sneakers",
		"schoolShoes",
		"flats",
		"girlsneakers",
		"boots",
		"heeledBoots",
		"highBoots",
		"highHeel3",
		"stilettoHeels",
		"balletHeels"
	],
	[
		"Accessories",
		"hairband",
		"hairbow",
		"choker",
		"collar",
		"collarSissy",
		"collarBitch",
		"collarSteel",
		"sunglasses",
		"glasses",
		"blindfold",
		"gag",
		"diamondStuds",
		"rubyEarrings",
		"hoopsEarrings",
		"plasticEarrings"
	],
	[
		"Toys",
		"chastityDevice",
		"buttPlugHeart",
		"buttPlugDildo",
		"buttPlugVibro",
		"buttPlugInflate"
	],
	[
		"Unsorted",
		"UnsortedName"
	]
];