window.itemTypes={
	NotClothing:   0,
	Underwear:     1,
	Outerwear:     2,
	Shoes:         4,
	Bras:          8,
	Chastity:     16,
	AnalPlug:     32,
	Stockings:    64,
	Earrings:    128,
	Collar:      256,
	Extra:       512,
	Hairband:   1024
},

window.quickSlotSets={
	School: 0,
	Casual: 3,
	Slutty: 6,
	Sleep: 9,
	Maid: 10,
	Cheerleader: 11
},

window.itemF={
	itemTwee: function(id) {
		if (State.active.variables.items[id] == null) {
			return false;
		}
		
		return State.active.variables.items[id];
	},
	name: function(item) {
		if (item == null) {
			return false;
		}
		if ((State.active.variables.items[item.id] != null) && (State.active.variables.items[item.id].name != null)) {
			return State.active.variables.items[item.id].name;
		}
		return item.name;
	},
	nameById: function(id) {
		if (window.itemsC[id] != null) {
			if ((State.active.variables.items[id] != null) && (State.active.variables.items[id].name != null)) {
				return State.active.variables.items[id].name;
			}
			return window.itemsC[id].name;
		}
		
		return false;
	},
	deleteItem: function(id) {
		delete State.active.variables.items[id];
	},
	image: function(item) {
		if (item == null) {
			return false;
		}
		if ((State.active.variables.items[item.id] != null) && (State.active.variables.items[item.id].image != null)) {
			return State.active.variables.items[item.id].image;
		}
		return item.image;
	},
	cost: function(item) {
		var oV;
		if (item == null) {
			return false;
		}
		if (item.cost == null) {
			return 0;
		}
		var cost=item.cost;
		var items=State.active.variables.items;
		oV=items[item.id];
		if ((oV != null) && (oV.cost != null)) {
			cost = oV.cost;
		}
		return cost;
	},
	disabled: function(item) {
		var oV;
		if (item == null) {
			return false;
		}
		if (item.disabled == null) {
			return false;
		}
		var disabled=item.disabled;
		var items=State.active.variables.items;
		oV=items[item.id];
		if ((oV != null) && (oV.disabled != null)) {
			disabled = oV.disabled;
		}
		return disabled;
	},
	daringRec: function(item) {
		var oV;
		if (item == null) {
			return false;
		}
		if (item.daringRec == null) {
			return 0;
		}
		var daringRec=item.daringRec;
		var items=State.active.variables.items;
		oV=items[item.id];
		if ((oV != null) && (oV.daringRec != null)) {
			daringRec = oV.daringRec;
		}
		return daringRec;
	},
},

window.itemsC={
	pyjamasMale : {
		id : "pyjamasMale",
		name: "Comfy pajamas",
		clothingType: window.itemTypes.Outerwear,
		cantWearWith: window.itemTypes.Underwear + window.itemTypes.Shoes + window.itemTypes.Stockings + window.itemTypes.Bras,
		ward: false,
		female: false,
		sleepWear: true,
		slutty: false,
		surgery: false,
		daringRec: 0,
		stolen: false,
		school: false,
		cheer: false,
		disabled: false,
		store: 5,
		cost: 20,
		maxAlt: 1,
		curAlt: 0,
		ownAlt: [],
		storeCur: 0,
		storeAlt: [],
		image: "male_pyjamas_"
	},
	silkyTeddy: {
		id: "silkyTeddy",
		name: "Nightie",
		store: 5,
		clothingType: window.itemTypes.Outerwear,
		cantWearWith: window.itemTypes.Underwear + window.itemTypes.Shoes + window.itemTypes.Bras,
		ward: false,
		female: true,
		slutty: false,
		school: false,
		cheer: false,
		stolen: false,
		sleepWear: true,
		disabled: false,
		surgery: false,
		daringRec: 5,
		cost: 65,
		maxAlt: 5,
		curAlt: 0,
		ownAlt: [],
		storeCur: 0,
		storeAlt: [],
		image: "nightie_"
	},
	casualMale : {
		id: "casualMale",
		name: "T-shirt and jeans",
		clothingType: window.itemTypes.Outerwear,
		cantWearWith: 0,
		ward: false,
		female: false,
		sleepWear: false,
		slutty: false,
		school: false,
		cheer: false,
		surgery: false,
		daringRec: 0,
		stolen: false,
		disabled: false,
		store: 4,
		cost: 0,
		maxAlt: 3,
		curAlt: 0,
		ownAlt: [],
		storeCur: 0,
		storeAlt: [],
		image: "tshirt_jeans_"
	},
	schoolMale : {
		id: "schoolMale",
		name: "School shirt, tie and pants",
		clothingType: window.itemTypes.Outerwear,
		cantWearWith: 0,
		ward: false,
		info: true,
		female: false,
		sleepWear: false,
		slutty: false,
		school: true,
		cheer: false,
		surgery: false,
		daringRec: 0,
		disabled: false,
		stolen: false,
		store: 4,
		cost: 0,
		image: "school_male.jpg"
	},
	schoolFemale : {
		id: "schoolFemale",
		name: "School dress",
		clothingType: window.itemTypes.Outerwear,
		cantWearWith: 0,
		ward: false,
		info: true,
		female: true,
		sleepWear: false,
		slutty: false,
		disabled: true,
		surgery: false,
		daringRec: 0,
		school: true,
		cheer: false,
		stolen: false,
		skirt: true,
		store: 4,
		cost: 90,
		maxAlt: 1,
		curAlt: 0,
		ownAlt: [],
		storeCur: 0,
		storeAlt: [],
		image: "school_female_"
	},
	sluttyschoolFemale : {
		id: "sluttyschoolFemale",
		name: "Slutty school dress",
		clothingType: window.itemTypes.Outerwear,
		cantWearWith: 0,
		ward: false,
		info: true,
		female: true,
		sleepWear: false,
		slutty: true,
		disabled: true,
		surgery: false,
		daringRec: 8,
		school: true,
		cheer: false,
		stolen: false,
		skirt: true,
		store: 4,
		cost: 0,
		image: "slutty_school_female.jpg"
	},
	rookieUniform : {
		id: "rookieUniform",
		name: "Cheerleader uniform",
		clothingType: window.itemTypes.Outerwear,
		cantWearWith: 0,
		ward: false,
		info: true,
		female: true,
		sleepWear: false,
		slutty: false,
		disabled: true,
		surgery: false,
		daringRec: 0,
		school: true,
		cheer: true,
		stolen: false,
		shorts: true,
		store: 4,
		cost: 0,
		image: "rookie_uniform.jpg"
	},
	cheerDress : {
		id: "cheerDress",
		name: "Cheerleader uniform",
		clothingType: window.itemTypes.Outerwear,
		cantWearWith: 0,
		ward: false,
		info: true,
		female: true,
		sleepWear: false,
		slutty: false,
		disabled: true,
		surgery: false,
		daringRec: 0,
		school: true,
		cheer: true,
		stolen: false,
		store: 4,
		cost: 0,
		image: "cheer_dress.jpg"
	},
	sluttyCheer : {
		id: "sluttyCheer",
		name: "Slutty cheerleader uniform",
		clothingType: window.itemTypes.Outerwear,
		cantWearWith: 0,
		ward: false,
		info: true,
		female: true,
		sleepWear: false,
		slutty: true,
		disabled: true,
		surgery: false,
		daringRec: 0,
		school: false,
		cheer: false,
		stolen: false,
		skirt: true,
		store: 4,
		cost: 0,
		maxAlt: 1,
		curAlt: 0,
		ownAlt: [],
		image: "slutty_cheer_"
	},	
	skirtTop : {
		id: "skirtTop",
		name: "Skirt and top",
		clothingType: window.itemTypes.Outerwear,
		cantWearWith: 0,
		ward: false,
		female: true,
		sleepWear: false,
		slutty: false,
		school: false,
		cheer: false,
		store: 4,
		stolen: false,
		skirt: true,
		surgery: false,
		daringRec: 5,
		disabled: false,
		cost: 60,
		maxAlt: 17,
		curAlt: 0,
		ownAlt: [],
		storeCur: 0,
		storeAlt: [],
		image: "skirt_top_"
	},
	summerDress: {
		id: "summerDress",
		name: "Light summer dress",
		clothingType: window.itemTypes.Outerwear,
		cantWearWith: 0,
		ward: false,
		female: true,
		sleepWear: false,
		slutty: false,
		school: false,
		cheer: false,
		store: 4,
		stolen: false,
		surgery: false,
		daringRec: 5,
		disabled: false,
		cost: 50,
		maxAlt: 35,
		curAlt: 0,
		ownAlt: [],
		storeCur: 0,
		storeAlt: [],
		image: "dress_casual_"
	},
	sluttyDress : {
		id: "sluttyDress",
		name: "Slutty dress",
		clothingType: window.itemTypes.Outerwear,
		cantWearWith: 0,
		ward: false,
		female: true,
		sleepWear: false,
		slutty: true,
		school: false,
		cheer: false,
		store: 4,
		stolen: false,
		surgery: false,
		daringRec: 7,
		disabled: false,
		cost: 160,
		alts: 3,
		maxAlt: 31,
		curAlt: 0,
		ownAlt: [],
		storeCur: 0,
		storeAlt: [],
		image: "dress_slutty_"
	},
	maidOutfit : {
		id: "maidOutfit",
		name: "Maid outfit",
		clothingType: window.itemTypes.Outerwear,
		cantWearWith: 0,
		ward: false,
		female: true,
		sleepWear: false,
		slutty: true,
		school: false,
		cheer: false,
		store: -1,
		stolen: false,
		surgery: false,
		daringRec: 13,
		disabled: false,
		cost: 0,
		maxAlt: 1,
		curAlt: 0,
		ownAlt: [],
		storeCur: 0,
		storeAlt: [],
		image: "maid_outfit_"
	},
	jocksLucky : {
		id: "jocksLucky",
		name: "Boxers",
		clothingType: window.itemTypes.Underwear,
		cantWearWith: 0,
		female: false,
		sleepWear: false,
		slutty: false,
		school: true,
		cheer: false,
		disabled: false,
		stolen: false,
		surgery: false,
		daringRec: 0,
		store: 5,
		cost: 10,
		maxAlt: 7,
		curAlt: 0,
		ownAlt: [],
		storeCur: 0,
		storeAlt: [],
		image: "lucky_jocks_"
	},
	bra: {
		id: "bra",
		name: "Bra",
		store: 5,
		clothingType: window.itemTypes.Bras,
		cantWearWith: 0,
		female: true,
		sleepWear: false,
		slutty: false,
		school: true,
		disabled: false,
		surgery: false,
		daringRec: 3,
		stolen: false,
		cost: 10,
		maxAlt: 22,
		curAlt: 0,
		ownAlt: [],
		storeCur: 0,
		storeAlt: [],
		image: "bra_"
	},
	braSexy: {
		id: "braSexy",
		name: "Lacy bra",
		store: 5,
		clothingType: window.itemTypes.Bras,
		cantWearWith: 0,
		female: true,
		sleepWear: false,
		slutty: true,
		school: true,
		disabled: false,
		surgery: false,
		daringRec: 4,
		stolen: false,
		cost: 40,
		maxAlt: 27,
		curAlt: 0,
		ownAlt: [],
		storeCur: 0,
		storeAlt: [],
		image: "bra_sexy_"
	},
	braLatex: {
		id: "braLatex",
		name: "Latex bra",
		store: 5,
		clothingType: window.itemTypes.Bras,
		cantWearWith: 0,
		female: true,
		sleepWear: false,
		slutty: true,
		school: true,
		disabled: false,
		surgery: false,
		daringRec: 6,
		stolen: false,
		cost: 150,
		maxAlt: 2,
		curAlt: 0,
		ownAlt: [],
		storeCur: 0,
		storeAlt: [],
		image: "bra_latex_"
	},
	pantiesCotton: {
		id: "pantiesCotton",
		name: "Panties",
		store: 5,
		clothingType: window.itemTypes.Underwear,
		cantWearWith: 0,
		female: true,
		sleepWear: false,
		slutty: false,
		school: true,
		cheer: false,
		stolen: false,
		surgery: false,
		daringRec: 3,
		disabled: false,
		cost: 15,
		maxAlt: 7,
		curAlt: 0,
		ownAlt: [],
		storeCur: 0,
		storeAlt: [],
		image: "panties_cotton_"
	},
	gString: {
		id: "gString",
		name: "Lacy panties",
		store: 5,
		clothingType: window.itemTypes.Underwear,
		cantWearWith: 0,
		female: true,
		sleepWear: false,
		slutty: true,
		school: true,
		cheer: false,
		disabled: false,
		surgery: false,
		daringRec: 3,
		stolen: false,
		cost: 55,
		maxAlt: 17,
		curAlt: 0,
		ownAlt: [],
		storeCur: 0,
		storeAlt: [],
		image: "panties_sexy_"
	},
	pantiesLatex: {
		id: "pantiesLatex",
		name: "Latex panties",
		store: 5,
		clothingType: window.itemTypes.Underwear,
		cantWearWith: 0,
		female: true,
		sleepWear: false,
		slutty: true,
		school: true,
		cheer: false,
		stolen: false,
		surgery: false,
		daringRec: 5,
		disabled: false,
		cost: 80,
		maxAlt: 2,
		curAlt: 0,
		ownAlt: [],
		storeCur: 0,
		storeAlt: [],
		image: "panties_latex_"
	},
	cheerBriefs: {
		id: "cheerBriefs",
		name: "Cheer briefs",
		store: 5,
		clothingType: window.itemTypes.Underwear,
		cantWearWith: 0,
		female: true,
		sleepWear: false,
		slutty: false,
		school: true,
		cheer: true,
		stolen: false,
		surgery: false,
		daringRec: 0,
		disabled: true,
		cost: 0,
		image: "cheer_briefs.jpg"
	},
	socks: {
		id: "socks",
		name: "Socks",
		store: 5,
		clothingType: window.itemTypes.Stockings,
		cantWearWith: 0,
		female: true,
		sleepWear: false,
		slutty: false,
		school: true,
		cheer: true,
		disabled: false,
		surgery: false,
		daringRec: 3,
		stolen: false,
		cost: 20,
		schoolAlt: 2,
		maxAlt: 24,
		curAlt: 0,
		ownAlt: [],
		storeCur: 0,
		storeAlt: [],
		image: "socks_"
	},
	stockings: {
		id: "stockings",
		name: "Stockings",
		store: 5,
		clothingType: window.itemTypes.Stockings,
		cantWearWith: 0,
		female: true,
		sleepWear: false,
		slutty: true,
		school: true,
		cheer: false,
		disabled: false,
		surgery: false,
		daringRec: 4,
		stolen: false,
		cost: 50,
		schoolAlt: 5,
		maxAlt: 27,
		curAlt: 0,
		ownAlt: [],
		storeCur: 0,
		storeAlt: [],
		image: "stockings_"
	},
	stockingsLatex: {
		id: "stockingsLatex",
		name: "Latex stockings",
		store: 5,
		clothingType: window.itemTypes.Stockings,
		cantWearWith: 0,
		female: true,
		sleepWear: false,
		slutty: true,
		school: true,
		cheer: false,
		disabled: false,
		surgery: false,
		daringRec: 6,
		stolen: false,
		cost: 200,
		schoolAlt: 0,
		maxAlt: 3,
		curAlt: 0,
		ownAlt: [],
		storeCur: 0,
		storeAlt: [],
		image: "stockings_latex_"
	},
	hairband: {
		id: "hairband",
		name: "Hairband",
		clothingType: window.itemTypes.Hairband,
		cantWearWith: 0,
		ward: false,
		store: 4,
		cost: 20,
		stolen: false,
		slutty: false,
		surgery: false,
		daringRec: 6,
		disabled: false,
		female: true,
		cheer: false,
		schoolAlt: 4,
		maxAlt: 9,
		curAlt: 0,
		ownAlt: [],
		storeCur: 0,
		storeAlt: [],
		image: "hairband_"
	},
	hairbow: {
		id: "hairbow",
		name: "Hairbow",
		clothingType: window.itemTypes.Hairband,
		cantWearWith: 0,
		ward: false,
		store: 4,
		cost: 10,
		stolen: false,
		slutty: false,
		surgery: false,
		daringRec: 5,
		disabled: false,
		female: true,
		cheer: true,
		schoolAlt: 0,
		maxAlt: 14,
		curAlt: 0,
		ownAlt: [],
		storeCur: 0,
		storeAlt: [],
		image: "hairbow_"
	},
	choker: {
		id: "choker",
		name: "Choker",
		clothingType: window.itemTypes.Collar,
		cantWearWith: 0,
		ward: false,
		store: 4,
		cost: 30,
		stolen: false,
		slutty: false,
		surgery: false,
		daringRec: 5,
		disabled: false,
		female: true,
		maxAlt: 7,
		curAlt: 0,
		ownAlt: [],
		storeCur: 0,
		storeAlt: [],
		image: "choker_"
	},
	collar: {
		id: "collar",
		name: "Collar",
		clothingType: window.itemTypes.Collar,
		cantWearWith: 0,
		ward: false,
		store: 3,
		cost: 50,
		stolen: false,
		slutty: true,
		surgery: false,
		daringRec: 6,
		disabled: false,
		female: true,
		maxAlt: 6,
		curAlt: 0,
		ownAlt: [],
		storeCur: 0,
		storeAlt: [],
		image: "collar_"
	},
	collarSissy: {
		id: "collarSissy",
		name: "Sissy collar",
		clothingType: window.itemTypes.Collar,
		cantWearWith: 0,
		ward: false,
		store: 3,
		cost: 50,
		stolen: false,
		slutty: true,
		surgery: false,
		daringRec: 9,
		disabled: false,
		female: true,
		maxAlt: 1,
		curAlt: 0,
		ownAlt: [],
		storeCur: 0,
		storeAlt: [],
		image: "collar_sissy_"
	},
	collarBitch: {
		id: "collarBitch",
		name: "Bitch collar",
		clothingType: window.itemTypes.Collar,
		cantWearWith: 0,
		ward: false,
		store: 3,
		cost: 50,
		stolen: false,
		slutty: true,
		surgery: false,
		daringRec: 8,
		disabled: false,
		female: true,
		image: "collar_bitch.jpg"
	},
	collarSteel: {
		id: "collarSteel",
		name: "Steel collar",
		clothingType: window.itemTypes.Collar,
		cantWearWith: 0,
		ward: false,
		store: 3,
		cost: 50,
		stolen: false,
		slutty: true,
		surgery: false,
		daringRec: 8,
		disabled: false,
		female: true,
		image: "collar_steel.jpg"
	},
	sunglasses: {
		id: "sunglasses",
		name: "Sunglasses",
		clothingType: window.itemTypes.Extra,
		cantWearWith: 0,
		ward: false,
		store: 4,
		cost: 20,
		stolen: false,
		slutty: false,
		surgery: false,
		daringRec: 0,
		disabled: false,
		female: false,
		maxAlt: 11,
		curAlt: 0,
		ownAlt: [],
		storeCur: 0,
		storeAlt: [],
		image: "sunglasses_"
	},
	glasses: {
		id: "glasses",
		name: "Decorative glasses",
		clothingType: window.itemTypes.Extra,
		cantWearWith: 0,
		ward: false,
		store: 4,
		cost: 20,
		stolen: false,
		slutty: false,
		surgery: false,
		daringRec: 0,
		disabled: false,
		female: false,
		maxAlt: 9,
		curAlt: 0,
		ownAlt: [],
		storeCur: 0,
		storeAlt: [],
		image: "glasses_"
	},
	blindfold: {
		id: "blindfold",
		name: "Blindfold",
		clothingType: window.itemTypes.Extra,
		cantWearWith: 0,
		ward: false,
		store: -1,
		cost: 20,
		stolen: false,
		slutty: false,
		surgery: false,
		daringRec: 0,
		disabled: false,
		female: false,
		maxAlt: 3,
		curAlt: 0,
		ownAlt: [],
		storeCur: 0,
		storeAlt: [],
		image: "blindfold_"
	},
	gag: {
		id: "gag",
		name: "Gag",
		clothingType: window.itemTypes.Extra,
		cantWearWith: 0,
		ward: false,
		store: -1,
		cost: 20,
		stolen: false,
		slutty: false,
		surgery: false,
		daringRec: 0,
		disabled: false,
		female: false,
		maxAlt: 10,
		curAlt: 0,
		ownAlt: [],
		storeCur: 0,
		storeAlt: [],
		image: "gag_"
	},
	diamondStuds: {
		id: "diamondStuds",
		name: "Casual earrings",
		clothingType: window.itemTypes.Earrings,
		cantWearWith: 0,
		ward: false,
		store: 4,
		cost: 50,
		stolen: false,
		slutty: false,
		surgery: false,
		daringRec: 6,
		disabled: false,
		female: true,
		maxAlt: 16,
		curAlt: 0,
		ownAlt: [],
		storeCur: 0,
		storeAlt: [],
		image: "earrings_casual_"
	},
	rubyEarrings: {
		id: "rubyEarrings",
		name: "Classy earrings",
		clothingType: window.itemTypes.Earrings,
		cantWearWith: 0,
		ward: false,
		store: 4,
		cost: 200,
		stolen: false,
		slutty: false,
		surgery: false,
		daringRec: 6,
		disabled: false,
		female: true,
		maxAlt: 16,
		curAlt: 0,
		ownAlt: [],
		storeCur: 0,
		storeAlt: [],
		image: "earrings_classy_"
	},
	hoopsEarrings: {
		id: "hoopsEarrings",
		name: "Flashy earrings",
		clothingType: window.itemTypes.Earrings,
		cantWearWith: 0,
		store: 4,
		cost: 100,
		stolen: false,
		slutty: true,
		surgery: false,
		daringRec: 6,
		disabled: false,
		female: true,
		maxAlt: 16,
		curAlt: 0,
		ownAlt: [],
		storeCur: 0,
		storeAlt: [],
		image: "earrings_flashy_"
	},
	plasticEarrings: {
		id: "plasticEarrings",
		name: "Plastic earrings",
		clothingType: window.itemTypes.Earrings,
		cantWearWith: 0,
		store: 4,
		cost: 20,
		stolen: false,
		slutty: true,
		surgery: false,
		daringRec: 6,
		disabled: false,
		female: true,
		maxAlt: 16,
		curAlt: 0,
		ownAlt: [],
		storeCur: 0,
		storeAlt: [],
		image: "earrings_plastic_"
	},
	sneakers: {
		id: "sneakers",
		name: "Sneakers",
		clothingType: window.itemTypes.Shoes,
		cantWearWith: 0,
		sleepWear: false,
		female: false,
		slutty: false,
		stolen: false,
		school: false,
		cheer: false,
		heels: false,
		disabled: false,
		surgery: false,
		daringRec: 0,
		store: 6,
		cost: 40,
		maxAlt: 3,
		curAlt: 0,
		ownAlt: [],
		storeCur: 0,
		storeAlt: [],
		image: "sneakers_"
	},
	schoolShoes: {
		id: "schoolShoes",
		name: "School shoes",
		clothingType: window.itemTypes.Shoes,
		cantWearWith: 0,
		sleepWear: false,
		female: false,
		school: true,
		cheer: false,
		heels: false,
		stolen: false,
		slutty: false,
		surgery: false,
		daringRec: 0,
		disabled: false,
		store: 6,
		cost: 40,
		maxAlt: 2,
		curAlt: 0,
		ownAlt: [],
		storeCur: 0,
		storeAlt: [],
		image: "black_shoes_"
	},
	flats: {
		id: "flats",
		name: "Flats",
		clothingType: window.itemTypes.Shoes,
		cantWearWith: 0,
		female: true,
		sleepWear: false,
		slutty: false,
		school: true,
		cheer: false,
		heels: false,
		store: 6,
		stolen: false,
		surgery: false,
		daringRec: 5,
		disabled: false,
		cost: 40,
		schoolAlt: 9,
		maxAlt: 33,
		curAlt: 0,
		ownAlt: [],
		storeCur: 0,
		storeAlt: [],
		image: "flats_"
	},
	girlsneakers: {
		id: "girlsneakers",
		name: "Girls' sneakers",
		clothingType: window.itemTypes.Shoes,
		cantWearWith: 0,
		female: true,
		sleepWear: false,
		slutty: false,
		school: false,
		cheer: false,
		heels: false,
		store: 6,
		stolen: false,
		surgery: false,
		daringRec: 5,
		disabled: false,
		cost: 60,
		maxAlt: 10,
		curAlt: 0,
		ownAlt: [],
		storeCur: 0,
		storeAlt: [],
		image: "girlsneakers_"
	},
	cheerSneakers: {
		id: "cheerSneakers",
		name: "Cheer sneakers",
		clothingType: window.itemTypes.Shoes,
		cantWearWith: 0,
		female: true,
		sleepWear: false,
		slutty: false,
		school: true,
		cheer: true,
		heels: false,
		store: 6,
		stolen: false,
		surgery: false,
		daringRec: 0,
		disabled: true,
		cost: 0,
		image: "cheer_sneakers.jpg"
	},
	heeledCheer: {
		id: "heeledCheer",
		name: "Heeled cheer sneakers",
		clothingType: window.itemTypes.Shoes,
		cantWearWith: 0,
		female: true,
		sleepWear: false,
		slutty: true,
		school: false,
		cheer: false,
		heels: true,
		store: 6,
		stolen: false,
		surgery: false,
		daringRec: 7,
		disabled: true,
		cost: 0,
		image: "heeled_cheer_sneakers.jpg"
	},
	boots: {
		id: "boots",
		name: "Women's boots",
		clothingType: window.itemTypes.Shoes,
		cantWearWith: 0,
		female: true,
		sleepWear: false,
		slutty: false,
		school: true,
		cheer: false,
		heels: false,
		store: 6,
		surgery: false,
		daringRec: 5,
		disabled: false,
		stolen: false,
		cost: 80,
		schoolAlt: 5,
		maxAlt: 21,
		curAlt: 0,
		ownAlt: [],
		storeCur: 0,
		storeAlt: [],
		image: "boots_"
	},
	heeledBoots: {
		id: "heeledBoots",
		name: "High-heeled boots",
		clothingType: window.itemTypes.Shoes,
		cantWearWith: 0,
		female: true,
		sleepWear: false,
		slutty: true,
		school: true,
		cheer: false,
		heels: true,
		store: 6,
		surgery: false,
		daringRec: 5,
		disabled: false,
		stolen: false,
		cost: 120,
		schoolAlt: 12,
		maxAlt: 23,
		curAlt: 0,
		ownAlt: [],
		storeCur: 0,
		storeAlt: [],
		image: "boots_heeled_"
	},
	highBoots: {
		id: "highBoots",
		name: "Thigh-high heeled boots",
		clothingType: window.itemTypes.Shoes,
		cantWearWith: 0,
		female: true,
		sleepWear: false,
		slutty: true,
		school: false,
		cheer: false,
		heels: true,
		store: 6,
		surgery: false,
		daringRec: 7,
		disabled: false,
		stolen: false,
		cost: 200,
		maxAlt: 13,
		curAlt: 0,
		ownAlt: [],
		storeCur: 0,
		storeAlt: [],
		image: "boots_high_"
	},
	highHeel3: {
		id: "highHeel3",
		name: "High heels",
		clothingType: window.itemTypes.Shoes,
		cantWearWith: 0,
		female: true,
		sleepWear: false,
		slutty: true,
		school: true,
		cheer: false,
		heels: true,
		store: 6,
		surgery: false,
		daringRec: 5,
		disabled: false,
		stolen: false,
		cost: 100,
		schoolAlt: 9,
		maxAlt: 18,
		curAlt: 0,
		ownAlt: [],
		storeCur: 0,
		storeAlt: [],
		image: "heels_"
	},
	stilettoHeels: {
		id: "stilettoHeels",
		name: "Stripper heels",
		clothingType: window.itemTypes.Shoes,
		cantWearWith: 0,
		female: true,
		sleepWear: false,
		slutty: true,
		school: false,
		cheer: false,
		heels: true,
		store: 6,
		surgery: false,
		daringRec: 7,
		disabled: false,
		stolen: false,
		cost: 300,
		maxAlt: 17,
		curAlt: 0,
		ownAlt: [],
		storeCur: 0,
		storeAlt: [],
		image: "heels_stripper_"
	},
	balletHeels: {
		id: "balletHeels",
		name: "Ballet heels",
		clothingType: window.itemTypes.Shoes,
		cantWearWith: 0,
		female: true,
		sleepWear: false,
		slutty: true,
		school: false,
		cheer: false,
		heels: true,
		store: -1,
		surgery: false,
		daringRec: 13,
		disabled: false,
		stolen: false,
		cost: 300,
		maxAlt: 13,
		curAlt: 0,
		ownAlt: [],
		storeCur: 0,
		storeAlt: [],
		image: "heels_ballet_"
	},
	chastityDevice: {
		id: "chastityDevice",
		name: "CB-6000 chastity device",
		clothingType: window.itemTypes.Chastity,
		cantWearWith: 0,
		store: 3,
		cost: 50,
		surgery: false,
		daringRec: 4,
		stolen: false,
		disabled: false,
		female: true,
		image: "chastity_cb6000.jpg"
	},
	buttPlugHeart: {
		id: "buttPlugHeart",
		name: "Butt-plug with jeweled heart",
		clothingType: window.itemTypes.AnalPlug,
		cantWearWith: 0,
		store: 3,
		cost: 40,
		surgery: false,
		daringRec: 4,
		stolen: false,
		disabled: false,
		female: true,
		image: "buttplug_heart.jpg"
	},
	buttPlugDildo: {
		id: "buttPlugDildo",
		name: "Butt-plug dildo",
		clothingType: window.itemTypes.AnalPlug,
		cantWearWith: 0,
		store: 3,
		cost: 80,
		stolen: false,
		surgery: false,
		daringRec: 6,
		disabled: false,
		female: true,
		image: "buttplug_dildo.jpg"
	},
	buttPlugVibro: {
		id: "buttPlugVibro",
		name: "Vibro butt-plug",
		clothingType: window.itemTypes.AnalPlug,
		cantWearWith: 0,
		store: -1,
		cost: 200,
		stolen: false,
		surgery: false,
		daringRec: 10,
		disabled: false,
		female: true,
		image: "buttplug_vibro.jpg"
	},
	buttPlugInflate: {
		id: "buttPlugInflate",
		name: "Inflatable butt-plug",
		clothingType: window.itemTypes.AnalPlug,
		cantWearWith: 0,
		store: -1,
		cost: 200,
		stolen: false,
		surgery: false,
		daringRec: 10,
		disabled: false,
		female: true,
		image: "buttplug_inflate_0.jpg"
	},
	remotePlugs: {
		id: "remotePlugs",
		name: "Remote controlled butt-plug",
		clothingType: window.itemTypes.NotClothing,
		cantWearWith: 0,
		store: 3,
		cost: 0,
		stolen: false,
		surgery: false,
		daringRec: 4,
		disabled: true,
		female: true,
		image: "buttplug_vibro.jpg"
	},
	alarmClock: {
		id: "alarmClock",
		name: "Alarm clock",
		store: 0,
		clothingType: window.itemTypes.NotClothing,
		disabled: false,
		surgery: false,
		daringRec: 0,
		image: "alarm_clock.jpg",
		stolen: false,
		cost: 15
	},
	batteries: {
		id: "batteries",
		name: "Batteries (Generic Brand)",
		store: 0,
		clothingType: window.itemTypes.NotClothing,
		disabled: false,
		surgery: false,
		daringRec: 0,
		stolen: false,
		image: "battery.jpg",
		cost: 5
	},
	batteriesQuality: {
		id: "batteriesQuality",
		name: "Batteries (Name Brand)",
		store: 0,
		clothingType: window.itemTypes.NotClothing,
		disabled: true,
		surgery: false,
		daringRec: 0,
		stolen: false,
		image: "battery_quality.jpg",
		cost: 10
	},
	spyCamera: {
		id: "spyCamera",
		name: "Wifi spy camera",
		store: 0,
		clothingType: window.itemTypes.NotClothing,
		disabled: false,
		surgery: false,
		daringRec: 0,
		stolen: false,
		image: "spy_camera.jpg",
		cost: 30
	},
	camera: {
		id: "camera",
		name: "Camera",
		store: 0,
		clothingType: window.itemTypes.NotClothing,
		disabled: false,
		surgery: false,
		daringRec: 0,
		stolen: false,
		image: "camera.jpg",
		cost: 0
	},
	stunGun: {
		id: "stunGun",
		name: "Stun gun",
		store: 0,
		clothingType: window.itemTypes.NotClothing,
		disabled: true,
		surgery: false,
		daringRec: 8,
		stolen: false,
		image: "stun_gun.jpg",
		cost: 200
	},
	roomGamer: {
		id: "roomGamer",
		name: "Video games themed decorations",
		store: 1,
		clothingType: window.itemTypes.NotClothing,
		disabled: false,
		surgery: false,
		daringRec: 0,
		stolen: false,
		image: "room_gamer.jpg",
		cost: 100
	},
	roomPunk: {
		id: "roomPunk",
		name: "Various punky decorations",
		store: 1,
		clothingType: window.itemTypes.NotClothing,
		disabled: false,
		surgery: false,
		daringRec: 0,
		stolen: false,
		image: "room_punk.jpg",
		cost: 80
	},
	roomGeek: {
		id: "roomGeek",
		name: "Fantasy themed decorations",
		store: 1,
		clothingType: window.itemTypes.NotClothing,
		disabled: false,
		surgery: false,
		daringRec: 0,
		stolen: false,
		image: "room_geek.jpg",
		cost: 120
	},
	roomSport: {
		id: "roomSport",
		name: "Sport themed decorations",
		store: 1,
		clothingType: window.itemTypes.NotClothing,
		disabled: false,
		surgery: false,
		daringRec: 0,
		stolen: false,
		image: "room_sport.jpg",
		cost: 90
	},
	roomGirly: {
		id: "roomGirly",
		name: "Girly girl room decorations",
		store: 1,
		clothingType: window.itemTypes.NotClothing,
		disabled: false,
		surgery: false,
		daringRec: 0,
		stolen: false,
		image: "room_girly_girl.jpg",
		cost: 0
	},
	lampClassic: {
		id: "lampClassic",
		name: "Classic lamp",
		store: 1,
		clothingType: window.itemTypes.NotClothing,
		disabled: false,
		surgery: false,
		daringRec: 0,
		stolen: false,
		image: "lamp_classic.jpg",
		cost: 20
	},
	lampPurple: {
		id: "lampPurple",
		name: "Purple lamp",
		store: 1,
		clothingType: window.itemTypes.NotClothing,
		disabled: false,
		surgery: false,
		daringRec: 0,
		stolen: false,
		image: "lamp_purple.jpg",
		cost: 35
	},
	lampTube: {
		id: "lampTube",
		name: "Multicolor lamp",
		store: 1,
		clothingType: window.itemTypes.NotClothing,
		disabled: false,
		surgery: false,
		daringRec: 0,
		stolen: false,
		image: "lamp_tube.jpg",
		cost: 25
	},
	vibrator: {
		id: "vibrator",
		name: "Vibrator",
		store: 3,
		clothingType: window.itemTypes.NotClothing,
		disabled: false,
		cost: 60,
		stolen: false,
		surgery: false,
		daringRec: 4,
		female: true,
		image: "vibrator.jpg"
	},
	massageOil: {
		id: "massageOil",
		name: "Sensuous massage oil",
		store: 3,
		clothingType: window.itemTypes.NotClothing,
		disabled: false,
		cost: 20,
		stolen: false,
		surgery: false,
		daringRec: 1,
		female: true,
		image: "massage_oil.jpg"
	},
	playgirlMagazine: {
		id: "playgirlMagazine",
		name: "Playgirl magazine",
		store: -1,
		clothingType: window.itemTypes.NotClothing,
		cost: 15,
		stolen: false,
		surgery: false,
		daringRec: 0,
		disabled: false,
		image: "playgirl_magazine.jpg",
		female: true
	},
	nailPolish: {
		id: "nailPolish",
		name: "Nail polish",
		store: 4,
		clothingType: window.itemTypes.NotClothing,
		cost: 10,
		stolen: false,
		surgery: false,
		daringRec: 0,
		disabled: true,
		female: true,
		image: "nail_polish.jpg"
	},
	Depilatory: {
		id: "Depilatory",
		name: "Depilatory",
		store: 2,
		clothingType: window.itemTypes.NotClothing,
		stolen: false,
		surgery: true,
		daringRec: 6,
		disabled: false,
		cost: 30,
		image: "hr_depilatory.jpg"
	},
	Waxing: {
		id: "Waxing",
		name: "Waxing",
		store: 2,
		clothingType: window.itemTypes.NotClothing,
		stolen: false,
		surgery: true,
		daringRec: 5,
		disabled: false,
		cost: 20,
		image: "hr_waxing.jpg"
	},
	LaserHairRemoval: {
		id: "LaserHairRemoval",
		name: "Laser hair removal",
		store: 2,
		clothingType: window.itemTypes.NotClothing,
		stolen: false,
		surgery: true,
		daringRec: 7,
		disabled: false,
		cost: 200,
		image: "hr_laser.jpg"
	},
	Manicure: {
		id: "Manicure",
		name: "Manicure",
		store: 2,
		clothingType: window.itemTypes.NotClothing,
		stolen: false,
		surgery: true,
		daringRec: 7,
		disabled: false,
		cost: 20,
		image: "manicure.jpg"
	},
	GarishManicure: {
		id: "GarishManicure",
		name: "Garish manicure",
		store: 2,
		clothingType: window.itemTypes.NotClothing,
		stolen: false,
		surgery: true,
		daringRec: 9,
		disabled: false,
		cost: 200,
		image: "manicure_garish.jpg"
	},
	PermanentManicure: {
		id: "PermanentManicure",
		name: "Garish manicure",
		store: 2,
		clothingType: window.itemTypes.NotClothing,
		stolen: false,
		surgery: true,
		daringRec: 9,
		disabled: false,
		cost: 200,
		image: "catalysator.jpg"
	},
	HairShort: {
		id: "HairShort",
		name: "Short haircut",
		store: 2,
		clothingType: window.itemTypes.NotClothing,
		stolen: false,
		surgery: true,
		daringRec: 5,
		disabled: false,
		cost: 20,
		image: "hair_short_brown.jpg"
	},
	HairMedium: {
		id: "HairMedium",
		name: "Medium haircut",
		clothingType: window.itemTypes.NotClothing,
		store: 2,
		stolen: false,
		surgery: true,
		daringRec: 6,
		disabled: false,
		cost: 30,
		image: "hair_medium_brown.jpg"
	},
	HairLong: {
		id: "HairLong",
		name: "Long haircut",
		clothingType: window.itemTypes.NotClothing,
		store: 2,
		stolen: false,
		surgery: true,
		daringRec: 6,
		disabled: false,
		cost: 50,
		image: "hair_long_brown.jpg"
	},
	HairPigtails: {
		id: "HairPigtails",
		name: "Pigtails",
		clothingType: window.itemTypes.NotClothing,
		store: 2,
		stolen: false,
		surgery: true,
		daringRec: 6,
		disabled: false,
		cost: 30,
		image: "hair_pigtails_brown.jpg"
	},
	HairCurly: {
		id: "HairCurly",
		name: "Curly hair",
		clothingType: window.itemTypes.NotClothing,
		store: 2,
		stolen: false,
		surgery: true,
		daringRec: 6,
		disabled: false,
		cost: 40,
		image: "hair_curly_brown.jpg"
	},
	SubtleMakeup: {
		id: "SubtleMakeup",
		name: "Subtle makeup",
		clothingType: window.itemTypes.NotClothing,
		store: 2,
		stolen: false,
		surgery: true,
		daringRec: 5,
		disabled: false,
		cost: 10,
		image: "makeup_subtle.jpg"
	},
	NormalMakeup: {
		id: "NormalMakeup",
		name: "Professional makeup",
		clothingType: window.itemTypes.NotClothing,
		store: 2,
		stolen: false,
		surgery: true,
		daringRec: 7,
		disabled: false,
		cost: 30,
		image: "makeup_normal.jpg"
	},
	BimboMakeup: {
		id: "BimboMakeup",
		name: "Bimbo makeup",
		clothingType: window.itemTypes.NotClothing,
		store: 2,
		stolen: false,
		surgery: true,
		daringRec: 7,
		disabled: false,
		cost: 50,
		image: "makeup_bimbo.jpg"
	},
	HeavyMakeup: {
		id: "HeavyMakeup",
		name: "Heavy makeup",
		clothingType: window.itemTypes.NotClothing,
		store: 2,
		stolen: false,
		surgery: true,
		daringRec: 8,
		disabled: false,
		cost: 15,
		image: "makeup_heavy.jpg"
	},
	PermanentSubtleMakeup: {
		id: "PermanentSubtleMakeup",
		name: "Permanent subtle makeup",
		clothingType: window.itemTypes.NotClothing,
		store: 2,
		stolen: false,
		surgery: true,
		daringRec: 9,
		disabled: false,
		cost: 100,
		image: "makeup_subtle.jpg"
	},
	PermanentNormalMakeup: {
		id: "PermanentNormalMakeup",
		name: "Permanent makeup",
		clothingType: window.itemTypes.NotClothing,
		store: 2,
		stolen: false,
		surgery: true,
		daringRec: 9,
		disabled: false,
		cost: 200,
		image: "makeup_normal.jpg"
	},
	PermanentBimboMakeup: {
		id: "PermanentBimboMakeup",
		name: "Permanent bimbo makeup",
		clothingType: window.itemTypes.NotClothing,
		store: 2,
		stolen: false,
		surgery: true,
		daringRec: 9,
		disabled: false,
		cost: 300,
		image: "makeup_bimbo.jpg"
	},
	PermanentHeavyMakeup: {
		id: "PermanentHeavyMakeup",
		name: "Permanent heavy makeup",
		clothingType: window.itemTypes.NotClothing,
		store: 2,
		stolen: false,
		surgery: true,
		daringRec: 10,
		disabled: false,
		cost: 200,
		image: "makeup_heavy.jpg"
	},
	tattooSissy: {
		id: "tattooSissy",
		name: "Sissy tattoo",
		clothingType: window.itemTypes.NotClothing,
		store: 2,
		stolen: false,
		surgery: false,
		daringRec: 8,
		disabled: false,
		cost: 10,
		image: "tattoo_sissy.jpg"
	},
	tattooSlut: {
		id: "tattooSlut",
		name: "Slut tattoo",
		clothingType: window.itemTypes.NotClothing,
		store: 2,
		stolen: false,
		surgery: false,
		daringRec: 8,
		disabled: false,
		cost: 60,
		image: "tattoo_slut.jpg"
	},
	tattooStupidWhore: {
		id: "tattooStupidWhore",
		name: "Stupid whore tattoo",
		clothingType: window.itemTypes.NotClothing,
		store: 2,
		stolen: false,
		surgery: false,
		daringRec: 8,
		disabled: false,
		cost: 40,
		image: "tattoo_stupidwhore.jpg"
	},
	tattooStockings: {
		id: "tattooStockings",
		name: "Stockings tattoo",
		clothingType: window.itemTypes.NotClothing,
		store: 2,
		stolen: false,
		surgery: false,
		daringRec: 7,
		disabled: false,
		cost: 80,
		image: "tattoo_stockings.jpg"
	},
	tattooHeart: {
		id: "tattooHeart",
		name: "Heart tattoo",
		clothingType: window.itemTypes.NotClothing,
		store: 2,
		stolen: false,
		surgery: false,
		daringRec: 8,
		disabled: false,
		cost: 15,
		image: "tattoo_heart.jpg"
	},
	tattooBunny: {
		id: "tattooBunny",
		name: "Bunny tattoo",
		clothingType: window.itemTypes.NotClothing,
		store: 2,
		stolen: false,
		surgery: false,
		daringRec: 7,
		disabled: false,
		cost: 20,
		image: "tattoo_bunny.jpg"
	},
	tattooButterfly: {
		id: "tattooButterfly",
		name: "Butterfly tattoo",
		clothingType: window.itemTypes.NotClothing,
		store: 2,
		stolen: false,
		surgery: false,
		daringRec: 7,
		disabled: false,
		cost: 100,
		image: "tattoo_butterfly.jpg"
	},
	beautyMark: {
		id: "beautyMark",
		name: "Beauty mark",
		clothingType: window.itemTypes.NotClothing,
		store: 2,
		stolen: false,
		surgery: false,
		daringRec: 7,
		disabled: false,
		cost: 10,
		image: "beauty_mark.jpg"
	},
	LipsEnhancing: {
		id: "LipsEnhancing",
		name: "Lips enhancing",
		clothingType: window.itemTypes.NotClothing,
		store: 2,
		stolen: false,
		surgery: true,
		daringRec: 7,
		disabled: false,
		cost: 30,
		image: "bm_lips.gif"
	},
	LipsEnhancingXL: {
		id: "LipsEnhancingXL",
		name: "Lips enhancing extra",
		clothingType: window.itemTypes.NotClothing,
		store: 2,
		stolen: false,
		surgery: true,
		daringRec: 8,
		disabled: false,
		cost: 100,
		image: "bm_lips_xl.gif"
	},
	LipsPermanent: {
		id: "LipsPermanent",
		name: "Lips permanent catalysator",
		clothingType: window.itemTypes.NotClothing,
		store: 2,
		stolen: false,
		surgery: true,
		daringRec: 9,
		disabled: true,
		cost: 500,
		image: "catalysator.jpg"
	},
	AssEnhancing: {
		id: "AssEnhancing",
		name: "Ass enhancing",
		clothingType: window.itemTypes.NotClothing,
		store: 2,
		stolen: false,
		surgery: true,
		daringRec: 7,
		disabled: false,
		cost: 30,
		image: "bm_ass.gif"
	},
	AssEnhancingXL: {
		id: "AssEnhancingXL",
		name: "Ass enhancing extra",
		clothingType: window.itemTypes.NotClothing,
		store: 2,
		stolen: false,
		surgery: true,
		daringRec: 8,
		disabled: false,
		cost: 100,
		image: "bm_ass_xl.gif"
	},
	AssPermanent: {
		id: "AssPermanent",
		name: "Ass permanent catalysator",
		clothingType: window.itemTypes.NotClothing,
		store: 2,
		stolen: false,
		surgery: true,
		daringRec: 9,
		disabled: true,
		cost: 500,
		image: "catalysator.jpg"
	},
	PenisShrinking: {
		id: "PenisShrinking",
		name: "Penis shrinking",
		clothingType: window.itemTypes.NotClothing,
		store: 2,
		stolen: false,
		surgery: true,
		daringRec: 9,
		disabled: true,
		cost: 20,
		image: "small_penis.jpg"
	},
	PiercingEars: {
		id: "PiercingEars",
		name: "Ears piercing",
		clothingType: window.itemTypes.NotClothing,
		store: 2,
		stolen: false,
		surgery: false,
		daringRec: 6,
		disabled: false,
		cost: 30,
		image: "piercing_ears.jpg"
	},
	PiercingLips: {
		id: "PiercingLips",
		name: "Lip piercing",
		clothingType: window.itemTypes.NotClothing,
		store: 2,
		stolen: false,
		surgery: false,
		daringRec: 7,
		disabled: false,
		cost: 20,
		image: "piercing_lips.jpg"
	},
	PiercingNose: {
		id: "PiercingNose",
		name: "Nose piercing",
		clothingType: window.itemTypes.NotClothing,
		store: 2,
		stolen: false,
		surgery: false,
		daringRec: 7,
		disabled: false,
		cost: 40,
		image: "piercing_nose.jpg"
	},
	PiercingBelly: {
		id: "PiercingBelly",
		name: "Belly piercing",
		clothingType: window.itemTypes.NotClothing,
		store: 2,
		stolen: false,
		surgery: false,
		daringRec: 7,
		disabled: false,
		cost: 50,
		image: "piercing_belly.jpg"
	},
	PiercingTongue: {
		id: "PiercingTongue",
		name: "Tongue piercing",
		clothingType: window.itemTypes.NotClothing,
		store: 2,
		stolen: false,
		surgery: false,
		daringRec: 7,
		disabled: false,
		cost: 30,
		image: "piercing_tongue.jpg"
	},
	PiercingNipples: {
		id: "PiercingNipples",
		name: "Nipples piercing",
		clothingType: window.itemTypes.NotClothing,
		store: 2,
		stolen: false,
		surgery: false,
		daringRec: 7,
		disabled: false,
		cost: 80,
		image: "piercing_nipples.jpg"
	},
	breastImplantsA: {
		id: "breastImplantsA",
		name: "Breast implants - small",
		clothingType: window.itemTypes.NotClothing,
		store: 2,
		stolen: false,
		surgery: true,
		daringRec: 6,
		disabled: false,
		cost: 50,
		image: "breast_implants_stage1.gif"
	},
	breastImplantsB: {
		id: "breastImplantsB",
		name: "Breast implants - average",
		clothingType: window.itemTypes.NotClothing,
		store: 2,
		stolen: false,
		surgery: true,
		daringRec: 6,
		disabled: false,
		cost: 100,
		image: "breast_implants_stage2.gif"
	},
	breastImplantsC: {
		id: "breastImplantsC",
		name: "Breast implants - big",
		clothingType: window.itemTypes.NotClothing,
		store: 2,
		stolen: false,
		surgery: true,
		daringRec: 7,
		disabled: false,
		cost: 200,
		image: "breast_implants_stage3.gif"
	},
	breastImplantsDD: {
		id: "breastImplantsDD",
		name: "Breast implants - massive",
		clothingType: window.itemTypes.NotClothing,
		store: 2,
		stolen: false,
		surgery: true,
		daringRec: 8,
		disabled: false,
		cost: 400,
		image: "breast_implants_stage4.gif"
	},
	breastPermanent: {
		id: "breastPermanent",
		name: "Breast permanent catalysator",
		clothingType: window.itemTypes.NotClothing,
		store: 2,
		stolen: false,
		surgery: true,
		daringRec: 9,
		disabled: true,
		cost: 1000,
		image: "catalysator.jpg"
	},
	analSmoothing1: {
		id: "analSmoothing1",
		name: "Anal smoothing",
		clothingType: window.itemTypes.NotClothing,
		store: 2,
		stolen: false,
		surgery: true,
		daringRec: 8,
		disabled: false,
		cost: 50,
		image: "ass_smoothening_1.jpg"
	},
	analSmoothing2: {
		id: "analSmoothing2",
		name: "Anal smoothing plus",
		clothingType: window.itemTypes.NotClothing,
		store: 2,
		stolen: false,
		surgery: true,
		daringRec: 9,
		disabled: false,
		cost: 100,
		image: "ass_smoothening_2.jpg"
	},
	analSmoothing3: {
		id: "analSmoothing3",
		name: "Anal smoothing extra",
		clothingType: window.itemTypes.NotClothing,
		store: 2,
		stolen: false,
		surgery: true,
		daringRec: 10,
		disabled: false,
		cost: 150,
		image: "ass_smoothening_3.jpg"
	},
	softeningFacial: {
		id: "softeningFacial",
		name: "Facial softening",
		clothingType: window.itemTypes.NotClothing,
		store: 2,
		stolen: false,
		surgery: true,
		daringRec: 7,
		disabled: false,
		cost: 100,
		image: "facial_softening.jpg"
	},
	surgeryFacial: {
		id: "surgeryFacial",
		name: "Facial softening extra",
		clothingType: window.itemTypes.NotClothing,
		store: 2,
		stolen: false,
		surgery: true,
		daringRec: 8,
		disabled: false,
		cost: 300,
		image: "facial_surgery.jpg"
	},
	noseClassic: {
		id: "noseClassic",
		name: "Classic nose",
		clothingType: window.itemTypes.NotClothing,
		store: 2,
		stolen: false,
		surgery: true,
		daringRec: 6,
		disabled: false,
		cost: 100,
		image: "nose_classic.jpg"
	},
	noseButton: {
		id: "noseButton",
		name: "Button nose",
		clothingType: window.itemTypes.NotClothing,
		store: 2,
		stolen: false,
		surgery: true,
		daringRec: 6,
		disabled: false,
		cost: 200,
		image: "nose_button.jpg"
	},
	nosePiggy: {
		id: "nosePiggy",
		name: "Piggy nose",
		clothingType: window.itemTypes.NotClothing,
		store: 2,
		stolen: false,
		surgery: true,
		daringRec: 6,
		disabled: false,
		cost: 20,
		image: "nose_piggy.jpg"
	},
	surgerySexualReassignment: {
		id: "surgerySexualReassignment",
		name: "Female sexual reassignment surgery",
		clothingType: window.itemTypes.NotClothing,
		store: 2,
		stolen: false,
		surgery: true,
		daringRec: 10,
		disabled: false,
		cost: 2000,
		image: "sexual_reassignment.jpg"
	},
	token : {
		id: "token",
		name: "token",
		clothingType: window.itemTypes.NotClothing,
		female: false,
		sleepWear: false,
		slutty: false,
		surgery: false,
		daringRec: 0,
		stolen: false,
		school: false,
		disabled: false,
		store: -1,
		cost: 0,
		image: "sexual_reassignment.jpg"
	}
},

window.itemSubTypes=[
	[
		"Outfits",
		"pyjamasMale",
		"silkyTeddy",
		"casualMale",
		"schoolMale",
		"schoolFemale",
		"sluttyschoolFemale",
		"rookieUniform",
		"cheerDress",
		"sluttyCheer",
		"skirtTop",
		"summerDress",
		"sluttyDress",
		"maidOutfit"
	],
	[
		"Undergarments",
		"jocksLucky",
		"bra",
		"braLatex",
		"braSexy",
		"pantiesCotton",
		"pantiesLatex",
		"gString",
		"cheerBriefs",
		"socks",
		"stockingsLatex",
		"stockings"
	],
	[
		"Footwear",
		"sneakers",
		"schoolShoes",
		"flats",
		"girlsneakers",
		"cheerSneakers",
		"heeledCheer",
		"boots",
		"heeledBoots",
		"highBoots",
		"highHeel3",
		"stilettoHeels",
		"balletHeels"
	],
	[
		"Accessories",
		"hairband",
		"hairbow",
		"choker",
		"collar",
		"collarSissy",
		"collarBitch",
		"collarSteel",
		"sunglasses",
		"glasses",
		"blindfold",
		"gag",
		"diamondStuds",
		"rubyEarrings",
		"hoopsEarrings",
		"plasticEarrings"
	],
	[
		"Toys",
		"chastityDevice",
		"buttPlugHeart",
		"buttPlugDildo",
		"buttPlugVibro",
		"buttPlugInflate"
	],
	[
		"Unsorted",
		"UnsortedName"
	]
];
